### ISSUE TITLE
Not an Issue :)

### ISSUE THREAD

**Issue by chsims1** [Saiyato/volumio-snapcast-plugin#1]
Nice to see someone's thinking about this.

Have you tried with librespot to see if Spotify will work as well?

**Comment by Saiyato** [comment]
No, I haven't been able to get that working yet... The latest version does install though and should work. Will update in a bit ;) (totally forgot to upload to github, have been quite occupied with other stuff)

**Comment by Saiyato** [comment]
I have created a first working release for MPD.

I have spotify-web-connect working, just not yet committed on github, configuration still needs some fine tuning.

Librespot should work, if compiled with the pipe backend, this needs some more testing on my side. As for the 'native' spotify plugin... no breakthrough just yet ;)

**Comment by chsims1** [comment]
Balbuze's volspotconnect2 (https://github.com/balbuze/volumio-plugins/tree/master/plugins/music_service/volspotconnect2) has librespot compiled with 'pipe' support, I believe.

**Comment by Saiyato** [comment]
Yes, I asked balbuze idd, I will check it in the near future. Just finished up the mpd (re)patch function and added it to the current release.
