### ISSUE TITLE
can't make New Client Plugin on volumio 3 work

### ISSUE THREAD

**Issue by karba78** [Saiyato/volumio-snapcast-plugin#100]
downloaded and installed the client plugin on volumio 3; thank you Saiyato. :)

no errors see below. Plugin config page works fine, no errors in changing parameters
but... does not play the server stream. only plays the local stream. which it should not play at all, .
i understand with volumio 3 we don't modify asound.conf anymore
is there additional manual config needed
thks

-----------
volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
nloading plugin at http://127.0.0.1:3000/plugin-serve/snapclient.zip
Progress: 30
Status :Creating install location
Creating install location
Progress: 40
Status :Unpacking plugin
Unpacking plugin
Progress: 45
Status :Checking that the plugin is suitable for this version of Volumio The plugin can be used with this version of Volumio
Checking that the plugin is suitable for this version of Volumio The plugin can be used with this version of Volumio
Progress: 50
Status :Checking for duplicate plugin
Checking for duplicate plugin
Progress: 60
Status :Copying plugin to location
Copying plugin to location
Progress: 70
Status :Installing necessary utilities
Installing necessary utilities
Progress: 70
Status :Installing necessary utilities
Installing SnapClient and dependencies...
Progress: 70
Status :Installing necessary utilities
## Installing SnapClient plugin v0.0.1 ##
Progress: 70
Status :Installing necessary utilities
Detecting CPU architecture and Debian version
Progress: 70
Status :Installing necessary utilities
CPU architecture:  armhf
Progress: 70
Status :Installing necessary utilities
Debian version:  buster
Progress: 70
Status :Installing necessary utilities
Fetching latest releases of SnapCast components...
Progress: 70
Status :Installing necessary utilities
(Reading database ... 52824 files and directories currently installed.)
Progress: 70
Status :Installing necessary utilities
Preparing to unpack .../snapclient_0.26.0-1_armhf.deb ...
Progress: 70
Status :Installing necessary utilities
Unpacking snapclient (0.26.0-1) over (0.15.0-1) ...
Progress: 70
Status :Installing necessary utilities
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Progress: 70
Status :Installing necessary utilities
Processing triggers for man-db (2.8.5-2) ...
Progress: 70
Status :Installing necessary utilities
(Reading database ... 52825 files and directories currently installed.)
Progress: 70
Status :Installing necessary utilities
Preparing to unpack .../snapclient_0.26.0-1_without-pulse_armhf.deb ...
Progress: 70
Status :Installing necessary utilities
Unpacking snapclient (0.26.0-1) over (0.26.0-1) ...
Progress: 70
Status :Installing necessary utilities
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Progress: 70
Status :Installing necessary utilities
Processing triggers for man-db (2.8.5-2) ...
Progress: 70
Status :Installing necessary utilities
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Progress: 70
Status :Installing necessary utilities
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Progress: 70
Status :Installing necessary utilities
Get:3 http://archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Progress: 70
Status :Installing necessary utilities
Hit:4 https://deb.nodesource.com/node_14.x buster InRelease
Progress: 70
Status :Installing necessary utilities
Fetched 426 kB in 5s (78.9 kB/s)
Progress: 70
Status :Installing necessary utilities
Reading package lists...
Progress: 70
Status :Installing necessary utilities
Reading package lists...
Progress: 70
Status :Installing necessary utilities
Building dependency tree...
Progress: 70
Status :Installing necessary utilities
Reading state information...
Progress: 70
Status :Installing necessary utilities
Correcting dependencies... Done
Progress: 70
Status :Installing necessary utilities
The following additional packages will be installed:
Progress: 70
Status :Installing necessary utilities
  libvorbisidec1
Progress: 70
Status :Installing necessary utilities
The following NEW packages will be installed:
Progress: 70
Status :Installing necessary utilities
  libvorbisidec1
Progress: 70
Status :Installing necessary utilities
0 upgraded, 1 newly installed, 0 to remove and 14 not upgraded.
Progress: 70
Status :Installing necessary utilities
1 not fully installed or removed.
Progress: 70
Status :Installing necessary utilities
Need to get 66.2 kB of archives.
Progress: 70
Status :Installing necessary utilities
After this operation, 127 kB of additional disk space will be used.
Progress: 70
Status :Installing necessary utilities
Get:1 http://mirrors.ircam.fr/pub/raspbian/raspbian buster/main armhf libvorbisidec1 armhf 1.2.1+git20180316-3 [66.2 kB]
Progress: 70
Status :Installing necessary utilities
Fetched 66.2 kB in 5s (12.6 kB/s)
Progress: 70
Status :Installing necessary utilities
Selecting previously unselected package libvorbisidec1.
Progress: 70
Status :Installing necessary utilities
(Reading database ... 52825 files and directories currently installed.)
Progress: 70
Status :Installing necessary utilities
Preparing to unpack .../libvorbisidec1_1.2.1+git20180316-3_armhf.deb ...
Progress: 70
Status :Installing necessary utilities
Unpacking libvorbisidec1 (1.2.1+git20180316-3) ...
Progress: 70
Status :Installing necessary utilities
Setting up libvorbisidec1 (1.2.1+git20180316-3) ...
Progress: 70
Status :Installing necessary utilities
Setting up snapclient (0.26.0-1) ...
Progress: 70
Status :Installing necessary utilities
Installing new version of config file /etc/default/snapclient ...
Progress: 70
Status :Installing necessary utilities
Installing new version of config file /etc/init.d/snapclient ...
Progress: 70
Status :Installing necessary utilities
Adding user `snapclient' to group `audio' ...
Progress: 70
Status :Installing necessary utilities
Adding user snapclient to group audio
Progress: 70
Status :Installing necessary utilities
Done.
Progress: 70
Status :Installing necessary utilities
insserv: warning: current start runlevel(s) (empty) of script `snapclient' overrides LSB defaults (2 3 4 5).
Progress: 70
Status :Installing necessary utilities
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `snapclient' overrides LSB defaults (0 1 6).
Progress: 70
Status :Installing necessary utilities
Processing triggers for libc-bin (2.28-10+rpt2+rpi1) ...
Progress: 70
Status :Installing necessary utilities
Processing triggers for systemd (241-7~deb10u8+rpi1) ...
Progress: 90
Status :Finalizing installation
Finalizing installation
Progress: 100
Status :SnapClient Successfully Installed, Do you want to enable the plugin now?
Finalizing installation
Done! Plugin Successfully Installed

**Comment by Saiyato** [comment]
Hi @karba78 ,

I can confirm indeed, hmmm.. after updating to the latest version it seems like the AAMP chain has been fully implemented. I will debug and see if I can patch soon.

**Comment by Saiyato** [comment]
Also I will add this issue to the correct repo, as this pertains to the new structure of SnapServer.

**Comment by Saiyato** [comment]
See: https://github.com/Saiyato/volumio-snapserver-plugin/issues/3

**Comment by karba78** [comment]
thank you @Saiyato 
would be keen to make it work with peppymetter, will post a different thread
