### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by webbes** [Saiyato/volumio-snapcast-plugin#11]
After updating to the version of juli 10th 2017 settings are not saved after hitting the save buttons at the specific sections.

**Comment by Saiyato** [comment]
Can you post the logs please? I've extensively tested the snapserver, snapclient and mpd sections. They are mostly unchanged (only snapserver has been modified). Spotify doesn't work yet, that is not uploaded yet.

**Comment by Saiyato** [comment]
See commit

**Comment by webbes** [comment]
You are awesome. Will test as soon as I can. (tomorrow?)
