### ISSUE TITLE
not an issue: snapcast volume control from volumio gui

### ISSUE THREAD

**Issue by cortegedusage** [Saiyato/volumio-snapcast-plugin#14]
Hi Saiyato,

loving your plugins, both this one as the kodi plugin.
But wouldn't it be nice to control the volume of snapcast from within the 
gui of volumio...

I ran into this one:
https://github.com/atoomic/snapcast-volume-ui

maybe something to integrate.

keep up the good work

"niet geschoten is altijd mis..."

**Comment by Saiyato** [comment]
I'm investigating ndjson messaging, because in order to achieve that I will need to message the snapserver API. I.e. I'm working on it ;)

**Comment by cortegedusage** [comment]
What is your view on this? Would it be possible to control all clients from within volumio gui?
Just interested...

**Comment by Saiyato** [comment]
That will take alot of extra work I presume, but I have to inventory the ndjson first. Because if I must dynamically draw volume controls for each new connected client and remove them upon closure.

Controlling volume through the UI for the local snapclient is much easier. I will focus on implementing that first.

Or is that what you mean? Control the local snapclient instance through the UI.

**Comment by cortegedusage** [comment]
Hi Saiyato,
I would like to have control of all the clients from one central point, so I can stay in the same volumio ui, select a room and set volume. 
I think https://github.com/atoomic/snapcast-volume-ui is just doing that.
it could be an extra link in the menu on the right side. with snapcast volume.

hmm offcourse when you only have volumio with snapcast running you could select the right room from the multiroom on the bottum of the screen and set volume from there.
most ideal with the volume knob already present in volumio. Is this what you had in mind?

anyway these are the thoughts of someone whose last programming steps were made in msx-basic.
So these are my 5cents... like to see how it develops in the future.

mucho gracias

Dennis

**Comment by Saiyato** [comment]
The UI volume control can now be used for a specific client. Multi volume control is not implemented, I don't really want to use python scripts for that, so we're going to need to investigate other possibilities.

**Comment by cortegedusage** [comment]
Sorry for the late reply,
but I must say you did a splendid job, it works like a charm...

but I can't seem to get volspotconnect2 to work....
but i'll live without until I got time to figure out what is wrong.
