### ISSUE TITLE
Sample rate for spotify integration setting

### ISSUE THREAD

**Issue by StefaanVanDooren** [Saiyato/volumio-snapcast-plugin#15]
Running Volumio 2,201, spotconnect2 and the latest snapcast plugin.

Music is played to fast and pitch is too high. When I manually add "sampleformat=44100:16:2" to the snapserver command all is good. Is there a way to set these settings for the spotify integration?

Generated by the plugin :
/usr/bin/snapserver -d --user snapserver:snapserver -d -s pipe:///tmp/snapfifo?name=VOLUMIO-MPD&mode=read&sampleformat=44100:16:2&codec=pcm -s pipe:///tmp/spotififo?name=Spotify&mode=read

Needed to play correct :
/usr/bin/snapserver -d --user snapserver:snapserver -d -s pipe:///tmp/snapfifo?name=VOLUMIO-MPD&mode=read&sampleformat=44100:16:2&codec=pcm -s pipe:///tmp/spotififo?name=Spotify&mode=read&sampleformat=44100:16:2

Also "Name of the Spotify stream" isn't saved between reboots.

**Comment by Saiyato** [comment]
Hi Stefaan,

I have not experienced high pitching noise @ 48kHz. I will implement functionality to adjust the Spotify sampling rate, bit depth and number of channels. Also I found that the Spotify stream name is set to undefined when changing MPD sound quality, will patch this as well.

**Comment by andrewj15** [comment]
Hi, Im having an issue where the music is playing too fast and at a high pitch in spotify. I have the sample rate set in the Spotify integration settings to 44100khz and the SnapServer setttings set at 48000khz. 

If i change the snapserver settings to 41000khz as well as the Spotify Integration settings at 41000khz then Spotify plays correctly at the right speed and pitch. However by doing this when playing local files or web radio it causes frequent dropouts and and plays at the wrong speed and pitch and is unlistenable. 

Likewise if I set both Spotify Integration settings and Snapserver sample rates to 48000khz Spotify plays to fast and at the wrong pitch. 

I'm using RPI3 for both client and server. I have the Snapcast Release from 24th September, volspotconnect2 v0.46 28th September release and Volumio 2.282

I had the same issue when using volspotconnect2 v0.40, Snapcast release 13th September and Volumio 2.246

Any help would be appreciated

**Comment by roland68** [comment]
Hello
I have the same issue with my USB-soundcard.
Playing over HDMI works fine. Is there any possibility to adjust the sample reate?
Any help is appreciated.

**Comment by Saiyato** [comment]
Hi Roland, take a look here: https://github.com/Saiyato/volumio-snapcast-plugin/issues/23
