### ISSUE TITLE
webUI setting page does not come

### ISSUE THREAD

**Issue by balbuze** [Saiyato/volumio-snapcast-plugin#17]
Hi!
I've just installed your plugin. Thank for all the work you have done.
device is pine64.
Install ok but can't display plugin settings ( empty page )
sudo journalctl -f returns :+1: 

> 

Aug 06 10:06:30 volumio-pine64 volumio[979]: info: snapserver started
Aug 06 10:06:30 volumio-pine64 volumio[979]: info: Done.
Aug 06 10:06:30 volumio-pine64 sudo[2638]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart snapclient
Aug 06 10:06:30 volumio-pine64 sudo[2638]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 06 10:06:30 volumio-pine64 systemd[1]: Starting Snapcast client...
Aug 06 10:06:30 volumio-pine64 snapclient[2641]: daemon started
Aug 06 10:06:30 volumio-pine64 systemd[1]: Started Snapcast client.
Aug 06 10:06:30 volumio-pine64 sudo[2638]: pam_unix(sudo:session): session closed for user root
Aug 06 10:06:30 volumio-pine64 volumio[979]: info: snapclient started
Aug 06 10:06:30 volumio-pine64 snapclient[2641]: Connected to 127.0.0.1
Aug 06 10:06:30 volumio-pine64 snapserver[2632]: StreamServer::NewConnection: 127.0.0.1
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: CoreCommandRouter::getUIConfigOnPlugin
Aug 06 10:06:42 volumio-pine64 systemd[1]: Starting Cleanup of Temporary Directories...
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: Loaded the previous config.
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , getDevices
Aug 06 10:06:42 volumio-pine64 systemd[1]: Started Cleanup of Temporary Directories.
Aug 06 10:06:42 volumio-pine64 snapserver[2632]: ControlServer::NewConnection: 127.0.0.1
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: ## populating UI...
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: 1/7 server settings loaded
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: 2/7 client settings loaded
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: 3/7 MPD settings loaded
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: 4/7 asound settings loaded
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: 5/7 spotify settings loaded
Aug 06 10:06:42 volumio-pine64 volumio[979]: info: 6/7 template settings loaded
Aug 06 10:06:42 volumio-pine64 snapserver[2632]: Exception in ControlSession::reader(): read_until: End of file
Aug 06 10:06:42 volumio-pine64 snapclient[2641]: Exception in Controller::worker(): sum timeout exceeded 10s
Aug 06 10:06:42 volumio-pine64 snapserver[2632]: Exception in StreamSession::reader(): read_some: End of file
Aug 06 10:06:42 volumio-pine64 snapserver[2632]: Session inactive. Removing
Aug 06 10:06:43 volumio-pine64 snapclient[2641]: Connected to 127.0.0.1
Aug 06 10:06:43 volumio-pine64 snapserver[2632]: StreamServer::NewConnection: 127.0.0.1
`

**Comment by Saiyato** [comment]
The problem is in the soundcard mapping, can you post the output of `cat /proc/asound` please?

**Comment by Saiyato** [comment]
I mean `ls -al /proc/asound` ofcourse ;)

**Comment by balbuze** [comment]
hi! here the content of ls -al /proc/asound

> volumio@volumio-pine64:~$ ls -al /proc/asound
total 0
dr-xr-xr-x   6 root root 0 Aug  6 20:44 .
dr-xr-xr-x 148 root root 0 Jan  1  1970 ..
lrwxrwxrwx   1 root root 5 Aug  6 20:44 FXAUDIOD802 -> card0
lrwxrwxrwx   1 root root 5 Aug  6 20:44 Loopback -> card7
lrwxrwxrwx   1 root root 5 Aug  6 20:44 audiocodec -> card1
dr-xr-xr-x   3 root root 0 Aug  6 20:44 card0
dr-xr-xr-x  10 root root 0 Aug  6 20:44 card1
dr-xr-xr-x   6 root root 0 Aug  6 20:44 card7
-r--r--r--   1 root root 0 Aug  6 20:44 cards
-r--r--r--   1 root root 0 Aug  6 20:44 devices
-r--r--r--   1 root root 0 Aug  6 20:44 hwdep
-r--r--r--   1 root root 0 Aug  6 20:44 pcm
dr-xr-xr-x   2 root root 0 Aug  6 20:44 seq
-r--r--r--   1 root root 0 Aug  6 20:44 timers
-r--r--r--   1 root root 0 Aug  6 20:44 version

**Comment by balbuze** [comment]
Just a thought, I didn't check if it can work, but in order to simplify the plugin maybe you should output to a virtual device (Loopback) and bridge the output of this device to the final output. In that way, you don't have to manage miscellaneous plugins as they are designed to be configured by volumio itself. It is what I did in volsimpleequal using alsaloop. But once again, I didn't check if it can work for snapcast.

**Comment by Saiyato** [comment]
I think I found where the mapping mismatch is happening, can you post back the contents of the ALSA (system) plugin configuration?

`cat /data/configuration/audio_interface/alsa_controller/config.json`

I think the outputdevice (string) is not in the list of soundcards I created based on the /proc/asound and Volumio cards.json.

I've patched the decorative soundcard display, can you check with the latest version?

**Comment by balbuze** [comment]
I'm going to test this soon. I keep you in touch.

**Comment by balbuze** [comment]
two things
- If I disable volsimpleequal (and then Loopback) the Ui comes !
- Can't install last version due to an error

> 

 info: Checking if plugin already exists
Aug 13 14:50:24 volumio-pine64 volumio[13010]: info: Rename folder
Aug 13 14:50:25 volumio-pine64 volumio[13010]: info: Move to category
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Checking if install.sh is present
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Executing install.sh
Aug 13 14:50:26 volumio-pine64 sudo[13186]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/sh /data/plugins//miscellanea/SnapCast/install.sh
Aug 13 14:50:26 volumio-pine64 sudo[13186]: pam_unix(sudo:session): session opened for user root by (uid=0)
Aug 13 14:50:26 volumio-pine64 sudo[13186]: pam_unix(sudo:session): session closed for user root
Aug 13 14:50:26 volumio-pine64 volumio[13010]: [140B blob data]
Aug 13 14:50:26 volumio-pine64 volumio[13010]: /data/plugins//miscellanea/SnapCast/install.sh: 108: /data/plugins//miscellanea/SnapCast/install.sh: Syntax error: word unexpected (expecting "in")
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Install script return the error Error: Command failed: echo volumio | sudo -S sh /data/plugins//miscellanea/SnapCast/install.sh > /tmp/installog
Aug 13 14:50:26 volumio-pine64 volumio[13010]: [140B blob data]
Aug 13 14:50:26 volumio-pine64 volumio[13010]: /data/plugins//miscellanea/SnapCast/install.sh: 108: /data/plugins//miscellanea/SnapCast/install.sh: Syntax error: word unexpected (expecting "in")
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: An error occurred installing the plugin. Rolling back config
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Plugin folders cleanup
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning into folder /volumio/app/plugins/
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category audio_interface
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category miscellanea
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category music_service
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category plugins.json
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category system_controller
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category user_interface
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning into folder /data/plugins/
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category miscellanea
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Plugin SnapCast found in folder but missing in configuration. Removing folder.
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Scanning category music_service
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Plugin folders cleanup completed
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Error: Error
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Installing SnapCast and its dependencies...
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Folder /tmp/downloaded_plugin removed
Aug 13 14:50:26 volumio-pine64 volumio[13010]: info: Folder /tmp/downloaded_plugin.zip removed
`

**Comment by Saiyato** [comment]
The new commit fixed this problem, line endings were Windows again. Sorry

**Comment by Saiyato** [comment]
Just found another problem, caused by the fix. Will have to investigate.
HifiBerry Digi doesn't work anymore, I am curious why it worked before, but in any case, I will need to patch this.

**Comment by balbuze** [comment]
I made a other test on a rpi with a usb FDA (full digital amplifier).
The output was ok in kodi asap I plug it. The configured volumio, and the usb output diseappears from kodi. 
What we can learn, the problem does not comes for i2S
So my guess (not proved ) is that volumio keep active the output and the kodi can't access it...Not sure but it needs more testing.

**Comment by Saiyato** [comment]
I think the above post was for the Kodi plugin, I placed it there ;)

**Comment by JoakimLindbom** [comment]
I believe this bug has resurfaced. I have 3 RPi:s running Volumio. On the one with Hifiberry DAC Plus the UI shows up fine, but on the one with Hifiberry Amp+ it does not. 
In /data/configuration/audio_interface/alsa_controller/config.json it's shown as:
...
  "outputdevicename": {
    "type": "string",
    "value": "HiFiBerry Amp"
  }
Not as Amp+ as I would expect.

I'm running Volumio 2.513, SnapCast 2.3.3 and Spotify Connect2 0.7.4
