### ISSUE TITLE
Pifi Dac issue (Hifiberry Dac Clone)

### ISSUE THREAD

**Issue by andrewj15** [Saiyato/volumio-snapcast-plugin#18]
I have updated to the latest version of snapcast and I am now unable to sync music on the client from the server. I believe it may be down to an issue in the plugin where the output device is listed as "no card match."

Previously it was working from Web radio and local files in sync but this was an older version from a few weeks ago.

I have a RPI 3b with pifi dac as the client device. 

![img_1682](https://user-images.githubusercontent.com/28840057/29523624-85d5b478-8685-11e7-924a-a50326598d73.PNG)
![img_1683](https://user-images.githubusercontent.com/28840057/29523625-85eefc30-8685-11e7-8f31-d868e232cf3c.PNG)

**Comment by Saiyato** [comment]
I don't think the volumio config should really matter, is decorative only.

Can you post the contents of /etc/snapclient please? You can obscure the IP-address if you want, I only need the global syntax and the part after `-s`.

**Comment by andrewj15** [comment]
Hi sorry, im a bit of a noob a this but when i SSH into the PI i can get to the etc directory a snapclient directory does not exist under etc. 
If i type snapclient when in the etc directory i get the following output

2017-08-21 15-11-09 [out] (Browser) CACHE_EXHAUSTED
2017-08-21 15-11-09 [out] (Browser) ALL_FOR_NOW

I can find a snapclient directory under /home/volumio/snapcast

volumio@kitchen:~/snapcast$ ls
index.html                     snapclient_0.11.1_armhf.deb.5
index.html.1                   snapserver_0.11.1_armhf.deb
snapclient_0.11.1_armhf.deb    snapserver_0.11.1_armhf.deb.1
snapclient_0.11.1_armhf.deb.1  snapserver_0.11.1_armhf.deb.2
snapclient_0.11.1_armhf.deb.2  snapserver_0.11.1_armhf.deb.3
snapclient_0.11.1_armhf.deb.3  snapserver_0.11.1_armhf.deb.4
snapclient_0.11.1_armhf.deb.4  snapserver_0.11.1_armhf.deb.5

If you could let me know the steps i need to take to get you the info and I will thanks

**Comment by Saiyato** [comment]
Yes you can use the following command `cat /etc/default/snapclient`

I see now I missed one directory level in my first remark. ;)

It should output something like this:

```
volumio@volumiomain:~$ cat /etc/default/snapclient
# defaults file for snapclient

# start snapclient automatically?
START_SNAPCLIENT=true

# Allowed options:
#   --help                          produce help message
#   -v, --version                   show version number
#   -h, --host arg                  server hostname or ip address
#   -p, --port arg (=1704)          server port
#   -l, --list                      list pcm devices
#   -s, --soundcard arg (=default)  index or name of the soundcard
#   -d, --daemon [=arg(=-3)]        daemonize, optional process priority [-20..1                                                9]
#   --user arg                      the user[:group] to run snapclient as when d                                                aemonized
#   --latency arg (=0)              latency of the soundcard
#   -i, --instance arg (=1)         instance id

USER_OPTS="--user snapclient:audio"

SNAPCLIENT_OPTS="-d -h 127.0.0.1 -s BossDAC"
```

**Comment by andrewj15** [comment]
Thanks here is my output:

```
volumio@kitchen:/$ cat /etc/default/snapclient
# defaults file for snapclient

# start snapclient automatically?
START_SNAPCLIENT=true

# Allowed options:
#   --help                          produce help message
#   -v, --version                   show version number
#   -h, --host arg                  server hostname or ip address
#   -p, --port arg (=1704)          server port
#   -l, --list                      list pcm devices
#   -s, --soundcard arg (=default)  index or name of the soundcard
#   -d, --daemon [=arg(=-3)]        daemonize, optional process priority [-20..19]
#   --user arg                      the user[:group] to run snapclient as when daemonized
#   --latency arg (=0)              latency of the soundcard
#   -i, --instance arg (=1)         instance id

USER_OPTS="--user snapclient:audio"

SNAPCLIENT_OPTS="-d -h 192.168.1.13 -s sndrpihifiberry"
```

One thing to note is the address 192.168.1.13 is the address of my snapcast server which is a Hifiberry Digi+ Pro note sure if that helps at all.

**Comment by Saiyato** [comment]
The output looks good, if you execute the following command, do you hear noise?

`sudo cat /dev/urandom > /tmp/snapfifo`

You can quit the noise by pressing ctrl+c.

If you hear noise, the problem is not the server/client stream. Maybe the MPD config is undone by Volumio, this is rewritten **every** time you change something in playback options.

**Comment by andrewj15** [comment]
I get a permission denied message when i try to execute that command

`-bash: /tmp/snapfifo: Permission denied
`
Ok not sure what happened there, but i went through all of the settings on both the client and server and saved them all as well as selecting to patch them and its now working in sync! Sorry about that and thanks for your help.
