### ISSUE TITLE
Spotify Connect (Snapcast not appearing as Spotify connect option)

### ISSUE THREAD

**Issue by andrewj15** [Saiyato/volumio-snapcast-plugin#19]
Hi, 

i'm having an issue getting snapcast to appear inside spotify with spotify connect. I am using volspotconnect2 v0.40 with a RPI 3B using a hifiberry Digi+ Pro and a Pifi Dac. I am able to get snapcast working for both web radio and local files from my NAS using the volumio web app. 
I have volumio 2.246 and I have your latest plugin from the 18th/19th august on both the client and server. I have spotify on both the mac desktop client as well as the iOS app but cannot see the Snapcast option on either.

However I cannot for the life of me see an option to get a snapcast stream appearing as a spotify connect option. Is there something stupid I am doing here? I have tried the settings on both the client and server but have not once seen a new spotify connect option. I only see the standard client and server streams that I had using volspotconnect prior to installing the snapcast plugin. I have tried with and without my spotify password and username i've attached my configuration within snapcast please let me know if there is any more info you need that will help.

**Server** 
<img width="671" alt="screen shot 2017-08-21 at 20 08 47" src="https://user-images.githubusercontent.com/28840057/29534212-1071c7c6-86ad-11e7-975e-534b92aa13da.png">

**Client**
<img width="713" alt="screen shot 2017-08-21 at 20 09 31" src="https://user-images.githubusercontent.com/28840057/29534211-106dc72a-86ad-11e7-9925-159b2e290c58.png">

**Comment by JeanPepin** [comment]
Hi,

I have exactly the same problem.
I am trying to use Spotify Connect with snapcast but it doesn't work.

Could you please help us by giving the way to configure server and client for Spotify Connect?

Thanks in advance,
Jean

**Comment by mattfield47** [comment]
I have the same problem with Spotify.  Tried both with and without a dedicated stream.  WebRadio and local files work fine.

**Comment by Saiyato** [comment]
Did you all install the Spotify plugin from balbuze, patch the templates and re-save your settings in the Spotify plugins?

**Comment by mattfield47** [comment]
Ah, so you need the spotify volumio plugin, the volspotconnect2 plugin _and_ snapcast plugin.  That helps and will give it a try tonight.

**Comment by Saiyato** [comment]
Aye, it's in the readme ;)

> 3. Spotify implementation: select the Spotify implementation you want to use (remember you still need to install needed plugins/binaries!).

**Comment by andrewj15** [comment]
Hi,  I have just tried what mattfield suggested, as i never had the spotify plugin installed only balbuze's volspotconnect2 plugin, however i am still not able to see an option in spotify connect for snapcast despite now having both plugins installed and active on both client and server.

**Comment by Saiyato** [comment]
There is no additional setting in the plugin, you just need to save your credentials again. A new template will be used to route the audio to snapserver.

**Comment by andrewj15** [comment]
So i have attempted again and patched the spotify template here 

<img width="989" alt="screen shot 2017-08-23 at 21 48 58" src="https://user-images.githubusercontent.com/28840057/29637721-ef05b31c-884c-11e7-9d7c-46477e9d9fa8.png">

And then saved the credentials in both the spotify plugins (spotify and volspotconnect2) however now i am unable to connect to either device in spotify. 

I retested this by factory resetting both devices and have found that I can connect in spotify after I install the snapcast plugin but not if i patch the spotify configuration templates. So I cannot get spotify connect to work as per your suggestion and if i do this it breaks my normal volspotconnect2 setup.

**Comment by Saiyato** [comment]
Is the result the same after a reboot of the machine?

Because not all restarts of the volspotconnect plugin succeed, sometimes the process seems to hang. Saving several times mostly solves my problems, or a reboot of course.

**Comment by andrewj15** [comment]
Yep, exactly the same, i tried saving both spotify plugins multiple times and have restarted the PI multiple times and its exactly the same result where spotify states connecting but reverts back to devices available after ~20 seconds

**Comment by andrewj15** [comment]
Let me know if you want any logs or other info that may help to debug this issue. I have left the one player in the state where it cannot connect to spotify. Also to note that in this state when launching the volumio Web ui for that player it will cause the loading cogs to display and reload each time I open the Web ui for that player.

**Comment by jkl55** [comment]
Hi, great plugin! NAS and web radio playback works perfectly. But I've the same issue when trying to use volspotconnect2 with snapcast.

**Comment by Saiyato** [comment]
Will setup a new volspotconnect2 rig this week, to retest.

**Comment by andrewj15** [comment]
Hi, over the weekend I tried your new version of the plugin but am still not able to get spotify connect working. I have only updated the client to the new version and this time I am able to connect on spotify to the client but do not hear any output via spotify. It still outputs when using local media or Web radio. I do not see another spotify connect option I just still see the client and server as options in spotify connect as previously. Could you let me know if there is something else I should try?

Thanks

**Comment by Saiyato** [comment]
Can you try restarting the snapserver component? Just save the snapserver settings, I've had the same problem until in reconfigured the server.

If that doesn't work can you post the contents of your startconnect.sh? Please do omit your credentials if they're in there.

`cat /data/plugins/music_service/volspotconnect2/startconnect.sh`

It should read something like this (I have not filled in my credentials):

```
volumio@VolumioAmp:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh 
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'VolumioAmp' --backend pipe --device /tmp/snapfifo
# --onstart ./onstart1.sh
```

Especially the --backend pipe and --device /tmp/snapfifo are important. If you are using a dedicated Spotify stream it probably reads /tmp/spotififo (depending on your config).

**Comment by andrewj15** [comment]
Hi I have now installed the sept 4th plugin on my server as well as the client. The client will connect to spotify and playback. 

The server however connects to spotify but will not output audio from spotify. Local music and Web Radio work fine on the server. 

I have ran the command you suggested and have the following output

```
volumio@livingroom:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'livingroom' --backend pipe --device /tmp/spotififo
# --onstart ./onstart1.sh
```

**Comment by Saiyato** [comment]
Hey mate,

You have configured an alternative stream for Spotify, have you connected to the right stream?
You must connect your clients to the dedicated Spotify stream, this might be what went wrong from the start in your setup.

This gives it away: `--device /tmp/spotififo`

Tick the dedicated stream to off; re-install the Spotify plugin (patching Spotify templates only works once); patch the Spotify plugin template and re-save your Spotify plugin settings.

**Comment by andrewj15** [comment]
Ok so, I have just updated both the client and the server to your latest file from today Sept 13th. Now I can get both devices to connect to spotify, the server plays spotify audio now, and this also comes through the client when spotify is connected to the server device. However if i just want to play spotify through the client, I do not get any audio despite it being shown as connected on the client.

The outputs are below:

Server
```
volumio@livingroom:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'livingroom' --backend pipe --device /tmp/snapfifo
# --onstart ./onstart1.sh
```

Client
```
volumio@kitchen:~$ #this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
volumio@kitchen:~$ cd /data/plugins/music_service/volspotconnect2
volumio@kitchen:/data/plugins/music_service/volspotconnect2$ ./librespot -b 320  -c /tmp  --name 'livingroom' --backend pipe --device /tmp/snapfifo
INFO:librespot: librespot ddfc28f (2017-08-04). Built on 2017-08-10. Build ID: Z3qO6N4b
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
INFO:librespot_core::session: Connecting to AP "***"
INFO:librespot_core::session: Authenticated as "*******" !
INFO:librespot_core::session: Country: "**"
```

**Comment by Saiyato** [comment]
If you want to use the client as a stand-alone device you shouldn't patch your Spotify plugin on your client device. Just keep the client as is, and just patch the server.

Depending on your use-case you could also setup multiple streams and switch stream when needed. This is easier using the Android client than the integrated ndjson way in my plugin.

**Comment by andrewj15** [comment]
Thank you so much! I have finally got it up and running and appreciate your last comment about not patching the client, as it now lets me use the client how I want to as either a stand alone device or a client for the server which is fantastic. 

It took me a while but i finally got there! Thanks for all your help. I don't have an Android client as am only on iOS so I don't think I will be playing with the multiple streams especially as i know have it up and running how I want it!

Awesome work on the plugin really appreciate it

**Comment by Saiyato** [comment]
Great! Glad to be of help, I'll try updating the readme a bit to clarify.

As for iOS, I'm not sure a client for iOS exists, but maybe someone has done the job already. ;)

**Comment by yayabobo** [comment]
Sorry to bother - also having a bit of a challenge with Spotify.  I have Snapcast up and running fine with local music and web radio - server (volumio) and client (volumio2) are in perfect synch.  Also, Spotify works fine on both server and client locally via SPOP.  I installed volspotconnect2 on both server and client, on the server I changed the stream to volspotconnect2, saved, patched, and saved the plugin to execute.  On the client I disabled dedicated stream, set to volspotconnect2 and saved.  Rebooted both devices... I can't seem to get a spotify song I play in my server to stream to both devices.  If I use the Spotify app on my phone I can connect to each device individually remotely - again, not streaming to each other.

Here are the outputs to the command you listed above...  

Server:
volumio@Volumio:/data$  cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'Volumio' --backend pipe --device /tmp/spotififo

Client:
volumio@volumio2:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'Volumio2' --backend alsa --device plughw:1 --disable-audio-cache --onstart ./onstart1.sh

First question - if I play a song via SPOP on the server, will it stream to the client, or does it only work remotely from another app like Spotify for IOS?

Second question - Any idea why it's not streaming to the client at all, even from Spotify app?  I think maybe the client has a problem with --name 'Volumio2', should be Volumio (name of my server, right?)  Can't seem to find where to change the source stream on the client.

Thanks for your help!

**Comment by Saiyato** [comment]
Will try to answer the above in issue #22
