### ISSUE TITLE
Out of Sync (~2sec delay

### ISSUE THREAD

**Issue by andrewj15** [Saiyato/volumio-snapcast-plugin#20]
Hi, 

I'm having an issue on the latest version where the client is ~2 secs delayed compared to the server. When i stop the client stream also turns off with the same delay. 

Im having this issue with web radio and local files. Previously on older versions the sync worked perfectly but not sure what the issue is as have checked all the settings and they all seem fine.

RPI 3B with Snapcast plugin from aug 18th. 

Thanks

**Comment by Saiyato** [comment]
Sounds like one of the clients is not using snapclient, but 'normal' ALSA output.

**Comment by andrewj15** [comment]
How would i go about fixing that? I have tried turning both on and off the ALSA setting in the snapcast plugin but the same results either way.

**Comment by Saiyato** [comment]
You can test this by listening to the Pi not running the server and e.g. an Android app. If those are in sync, it's most definitely not a snapcast problem.

**Comment by andrewj15** [comment]
Ok i've done a fresh install on both client and server and it is working in sync correctly now, thanks for your help :)
