### ISSUE TITLE
Snapcast+Volspotconnect2+Spop - no Spotify Stream to Client

### ISSUE THREAD

**Issue by yayabobo** [Saiyato/volumio-snapcast-plugin#22]
Hey Saiyato!  Love the project, thanks for all that you do... not sure if I am having problems similar to others or something new.  Posted on the Volumio forum but not getting very far...

Am using your snapcast installer, Volumio's built in SPOP plugin for Spotify and balbuze's volsporconnect2 plugin. I have Snapcast up and running fine with local music and web radio - server (hostname volumio) and client (hostname volumio2) are in perfect synch. Also, Spotify works fine on both server and client locally via SPOP. Per your readme I installed volspotconnect2 on both server and client, on the server I changed the stream to volspotconnect2, saved, patched, and saved the plugins to execute. On the client I disabled dedicated stream, set to volspotconnect2 and saved (no patch). Rebooted both devices... I can't seem to get a Spotify song I play in my server to stream to both devices in synch. If I use the Spotify app on my phone I can connect to each device individually remotely - again, not streaming to each other.

Here is the volspotconnect2 config:

Server:
volumio@Volumio:/data$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320 -c /tmp --name 'Volumio' --backend pipe --device /tmp/spotififo

Client:
volumio@volumio2:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320 -c /tmp --name 'Volumio2' --backend alsa --device plughw:1 --disable-audio-cache --onstart ./onstart1.sh

Any help is appreciated - sorry for the newbie questions!

**Comment by yayabobo** [comment]
Thank you - one other point, I tried it both ways, but should the server be running a dedicated stream or integrated (client is not).

I am traveling for three days so may not be able to respond, so no rush, just when you get a chance.

Thanks!

**Comment by yayabobo** [comment]
Back from travel - any ideas?

**Comment by Saiyato** [comment]
I'm not entirely sure what it is that you want to achieve. Can you clarify please?

Are you trying to setup a server and a 'hybrid' device (snapclient + stand-alone Volumio)? I've updated the readme. The hybrid device should not have a snapserver, just the client.

Also if you are using dedicated Spotify streams, please read the SnapCast documentation, I wouldn't recommend this if you aren't experienced with the matter.

**Comment by yayabobo** [comment]
Sorry - didn't mean to confuse.... yes, it is two volumio RP3 boxes, one acting as server, one as a hybrid client.  WebRadio/NAS works fine, just an issue with Spotify.  I've followed the instructions, patched, rebooted, reinstalled and tried again, etc... still no luck.

Here is an imgur album for my configuration - Server pics are first:  https://imgur.com/a/Rjpri

Here is the server volspotconnect2 output:
volumio@volumio:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'Volumio' --backend pipe --device /tmp/snapfifo

Here is the client volspotconnect2 output:
volumio@volumio2:~$ cat /data/plugins/music_service/volspotconnect2/startconnect.sh
#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'Volumio2' --backend alsa --device plughw:1 --disable-audio-cache --onstart ./onstart1.sh

Let me know if there is any troubleshooting you recommend.  I appreciate your time and help!

**Comment by Saiyato** [comment]
Can you post the results of `cat /etc/default/snapserver` please? That is the snapserver config and will show you what fifo will be served to clients.

**Comment by yayabobo** [comment]
Here you go:

volumio@volumio:~$ cat /etc/default/snapserver
# defaults file for snapserver

# start snapserver automatically?
START_SNAPSERVER=true

# Allowed options:
#   -h, --help                          Produce help message
#   -v, --version                       Show version number
#   -p, --port arg (=1704)              Server port
#   --controlPort arg (=1705)           Remote control port
#   -s, --stream arg (=pipe:///tmp/snapfifo?name=default)
#                                       URI of the PCM input stream.
#                                       Format: TYPE://host/path?name=NAME
#                                       [&codec=CODEC]
#                                       [&sampleformat=SAMPLEFORMAT]
#   --sampleformat arg (=48000:16:2)    Default sample format
#   -c, --codec arg (=flac)             Default transport codec
#                                       (flac|ogg|pcm)[:options]
#                                       Type codec:? to get codec specific options
#   --streamBuffer arg (=20)            Default stream read buffer [ms]
#   -b, --buffer arg (=1000)            Buffer [ms]
#   -d, --daemon [=arg(=0)]             Daemonize
#                                       optional process priority [-20..19]
#   --user arg                          the user[:group] to run snapserver as when daemonized

USER_OPTS="--user snapserver:snapserver"

SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=VOLUMIO-MPD&mode=read"
volumio@volumio:~$

**Comment by yayabobo** [comment]
Here you go, removed the comments:

volumio@volumio:~$ cat /etc/default/snapserver

START_SNAPSERVER=true

USER_OPTS="--user snapserver:snapserver"

SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=VOLUMIO-MPD&mode=read"
volumio@volumio:~$

**Comment by Saiyato** [comment]
Ok, I will try to explain what is happening:

1. The volspotconnect2 on your server will send the audio to /tmp/snapfifo
2. The SnapServer component will be reading the /tmp/snapfifo file and serving it
3. The SnapClient component will be reading audio chunks sent by a connected server

How are you trying to playback to the server? You must connect to your server in Spotify, it's not syncing all your Spotify playback automatically.

**Comment by yayabobo** [comment]
Ah I see - I was just trying to use the native spotify plugin in the Volumio server webapp... and wanting it to play on both RP3s... when I play from my spotify app on my phone it works.

So there is no way to control the Spotify multiroom from within the webapp?

**Comment by Saiyato** [comment]
Yeah there is, but you need to select SPOP as your implementation in the snapcast plugin; then patch that config; then resave the config in the SPOP plugin.

SPOP = the 'native' Spotify plugin.

**Comment by yayabobo** [comment]
Ah ok, let me give that a shot - thank you again.

**Comment by Saiyato** [comment]
Awesome! If you have doubts just check /etc/spopd.conf it should contain a raw output where the name should be /tmp/snapfifo

**Comment by yayabobo** [comment]
You're going to laugh - worked fine the first time... I'm hearing out of both speakers, but the sounds is a bit pitched - like a tiny bit fast (almost like chipmonks).... any idea what could cause that?

:edit: 
Tried rebooting, same issue

:Edit2:
Looks like I am getting the same issue as https://github.com/Saiyato/volumio-snapcast-plugin/issues/23 - I will watch there.

I am all good here, thank you!

**Comment by yayabobo** [comment]
Just wanted to say thank you for everything... I am 100% set - appreciate all your hard work for the community!

**Comment by cerbera79** [comment]
Hi guys, I know I'm a little late, but which one is the native Spotify SPOP plugin? Volumio Spotify Connect 2 (v 0.9.5) or the Spotify plugin (v 1.3.5) at the volumio plugin site?

I'm having a similar issue in getting Spotify to play from my phone to the snapserver and then onto the local client. (Webradio works really well).

**Comment by karba78** [comment]
I got this working this week by commenting the hw section in mpd.conf, but it did not last. my files db got corrupted and mpd would not rebuild it, had to reset and cant get it to work again. 
I am posting my files below if @Saiyato has a couple of minutes to look at it, or someone else who managed to get it working..
-------------------------------------------------------
# Volumio MPD Configuration File

# Files and directories #######################################################
music_directory         "/var/lib/mpd/music"
playlist_directory              "/var/lib/mpd/playlists"
db_file                 "/var/lib/mpd/tag_cache"
log_file                        "/var/log/mpd.log"
#pid_file                       "/var/run/mpd/pid"
#state_file                     "/var/lib/mpd/state"
#sticker_file                   "/var/lib/mpd/sticker.sql"
###############################################################################

# General music daemon options ################################################
user                            "mpd"
group                          "audio"
bind_to_address         "any"
#port                           "6600"
#log_level                      "default"
gapless_mp3_playback                    "no"
#save_absolute_paths_in_playlists       "no"
#metadata_to_use        "artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update    "yes"
#auto_update_depth "3"
###############################################################################
# Symbolic link behavior ######################################################
follow_outside_symlinks "yes"
follow_inside_symlinks          "yes"
###############################################################################
# Input #######################################################################
#
input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}
###############################################################################

# Decoder ################################################################





###############################################################################

# Audio Output ################################################################

resampler {
                plugin "soxr"
                quality "high"
                threads "1"
}

audio_output {
                type            "alsa"
                enabled         "no"
                name            "alsa"
                device          "hw:1,0"
                dop                     "no"




}





audio_output {
    type            "fifo"
    enabled         "yes"
    name            "multiroom"
    path            "/tmp/snapfifo"
    format          "44100:16:2"
}

#replaygain                     "album"
#replaygain_preamp              "0"
volume_normalization            "no"
###############################################################################

# MPD Internal Buffering ######################################################
audio_buffer_size               "2048"
buffer_before_play              "10%"
###############################################################################


# Resource Limitations ########################################################
#connection_timeout             "60"
max_connections                 "20"
max_playlist_length             "81920"
max_command_list_size           "81920"
max_output_buffer_size          "81920"
###############################################################################

# Character Encoding ##########################################################
filesystem_charset              "UTF-8"
id3v1_encoding                  "UTF-8"
###############################################################################
---------------spopd file------------------------------
[spop]
spotify_username = yyyy
spotify_password = xxxx
high_bitrate = true
refresh_token = none
audio_output = sox
pretty_json = true
search_results = 50
cache_path =/run/shm

[sox]
output_type = raw
output_name = /tmp/snapfifo

-------------snapserver config files-------------------------

USER_OPTS="--user snapserver:snapserver"

SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=VOLUMIO-MPD&mode=read&sampleformat=44100:16:2 "
--------------snapserver client files--------------

USER_OPTS="--user snapclient:audio"

SNAPCLIENT_OPTS="-d -h 192.168.0.242 -s IQaudIODAC "
------------------------------------------------
