### ISSUE TITLE
libatomic1 not installed

### ISSUE THREAD

**Issue by bdynamic** [Saiyato/volumio-snapcast-plugin#26]
I just tried to install the snapcast plugin on a Volumio Version 2.296 (not clean installation) and  Volumio Version 2.310 (new and clean installation)
Server could be started but not the client (error message when changing the client settings) "could not start snapclient"

Commandline confirmed this.

Solution: Manually install libatomic1 which was apparently missing via ssh
sudo apt-get install libatomic1

This solves the issue

**Comment by Saiyato** [comment]
Which version of the plugin did you use?

**Comment by bdynamic** [comment]
I downloaded yesterday Zip directly  from here (git)

**Comment by Saiyato** [comment]
What platform are you running? Raspberry Pi? (1, 2 or 3)

I will re-setup my Pi2 with HifiBerry Amp (version 2.296 did install without problems).

**Comment by Hellwo** [comment]
I can confirm the issue, happened to me too but only on my raspberry pi zero w. My RPi Model B had no issues installing it. Latest Volumio Version running (2.2323)

**Comment by Saiyato** [comment]
So it seems like the problem is only with the Pi Zero W, as I don't have one yet, I'm not sure how to fix the issue. Is it possible to positively identify the Zero W in shell?

**Comment by bdynamic** [comment]
Sorry - although it sound wired this is not the case. The Volumio Installation 2.296 runs on a Raspberry 3, the 2.310 on a Raspberry 1 Model B

**Comment by bdynamic** [comment]
Suggestion / stupid question: Is the libatomic1 in the installation candidates of the installation script?
I mean - obviously it is required and it should be installed if you put it there. Most likely you are doing this and out of a strange reason it is not installed?

**Comment by Saiyato** [comment]
I've just experienced this for the first time and I have a fix that'll probably work.
Just flashed the SD card, I will test with the new package now.
