### ISSUE TITLE
Volumio and Snapcast

### ISSUE THREAD

**Issue by hpswalters** [Saiyato/volumio-snapcast-plugin#29]
To start, I'm very pleased with the work you have done.  
As you might suspect, I am attempting a muti-room, sonos-like playback of music from  my network and I have it working --for the most part.  The system consists of a Pi3 as the server, four Pi2's and two Pi0's as the clients.  the Pi0's have a HiFiberry compatible DACs and work just fine.

However, two of My Pi2's have the Pi2 Design 503 Hybrid Tube Amp and when I install the SnapCast they stop working altogether--this is without even activating SnapCast.  My hypothesis is that SnapCast does list the correct "Soundcard to Use for Playback" in the setup.  The pictures below hopefully illustrate the problem.

![image](https://user-images.githubusercontent.com/29784448/34729695-6f12de18-f52b-11e7-8847-02fc12fa7592.png)

Unfortunately, this option does not appear in the SnapCast Settings.
![image](https://user-images.githubusercontent.com/29784448/34729820-b301c8fa-f52b-11e7-92ba-8546992adf36.png)

Is there a config file I can modify to get the correct playback options

Thanks,
-hpw

**Comment by hpswalters** [comment]
I have answered my own question -- although I don't understand why/how.  The Pi2's with Pi2 Design 503 Hybrid Tube Amp worked when I enabled the SnapCast Server and subscribed to the stream from the Pi3.  This seems particularly odd since I have the servers disabled on all other Pi's

Any insights into what is happening?

-hpw

**Comment by Saiyato** [comment]
I'm not sure how the tube amp works, so I'm affraid this is difficult for me to answer.
You should be able to only use the client on the Pi2's, if you connect to the Pi3 the server will do nothing at all.

The plugin installs the snapcast client, patches mpd.conf, sets the parameters for the snapcast client and restarts it.

You can list the compatible soundcards using the following command (the plugin does the same):

> snapclient -l

That should work imho. You can check it by reading /etc/default/snapclient, it should contain the following:

-d = run as daemon
-h {IP} = the host IP-address
-s {SOUNDCARD} = the configured soundcard

Maybe the snapclient just needed a restart to load the soundcard.

Please let me know if this helps you.

**Comment by Saiyato** [comment]
Have you had any success with the Tube Amp?
