### ISSUE TITLE
/tmp filling up - music stops playing

### ISSUE THREAD

**Issue by steubens** [Saiyato/volumio-snapcast-plugin#30]
@Saiyato, please reference the below-linked discussion we had a few months ago on volumio forums.  I had stopped using your plugin because of this issue and have been having no issues using volspotconnect2 with volumio for months now. I have just yesterday downloaded the latest version of your plugin and reinstalled. Again I'm seeing the /tmp folder filling up after 4 or so hours of playing; a reboot will empty it out and give me another 4 hours until it stops playing again.

Were you ever able to implement the change you mentioned in your last forum message - Getting rid of the cache option from the volspotconnect2 template? 
I'm still seeing `-c /tmp` in `startconnect.sh`...

![image](https://user-images.githubusercontent.com/6864307/34808319-2b9b5408-f65c-11e7-818a-7800b354e001.png)

**Forum Discussion:**
[https://volumio.org/forum/tmp-partition-filling-using-snapcast-spotify-t8020.html?hilit=snapcast#p40538](https://volumio.org/forum/tmp-partition-filling-using-snapcast-spotify-t8020.html?hilit=snapcast#p40538)

Thanks!

**Comment by Saiyato** [comment]
Hi,

I have been kept busy with other work, but I'll try to update this week. Apologies for the delay.

**Comment by steubens** [comment]
@Saiyato - you're awesome! I installed the new version and no longer having music cut out because of filled up /tmp partition.  Many thanks!!

**Comment by Saiyato** [comment]
Glad to be of help! Enjoy :)
