### ISSUE TITLE
Snapcast with other media sources than spotify

### ISSUE THREAD

**Issue by Gronis** [Saiyato/volumio-snapcast-plugin#33]
Hi, great plugin. Works really good for enabling spotify connect on multiroom/multidevice DIY music systems.

However, I cannot get it to work with other media sources (like playing media files from a NAS or Airplay). Does it support other media sources, and how do I enable that on my clients?

**Comment by Saiyato** [comment]
This requires knowledge about SoX I guess... You can try to copy the mpd config to Airplay/DLNA play
