### ISSUE TITLE
Specify snapcast server and client CLI flags

### ISSUE THREAD

**Issue by Gronis** [Saiyato/volumio-snapcast-plugin#34]
It would be nice to be able to specify CLI arguments in snapcast settings for both snapclient and snapserver. You could manually edit the files in /etc/default, but that is not very user friendly. Also if you change any other setting which overwrite these files, you have to go in and change them again.

I've been tweeking with buffersize for snapserver. This parameter specify the delay between audio is fed to the fifo pipe, and when the client reads the data. The default is 1000ms which in my opinion adds to much delay for responsive audio control. Too be able to specify this in the plug-in settings would be nice.

For the client, there is a latency flag which can be used to correctly sync clients depending on the response time on different audio systems. This setting have to be tuned by hand for the best experience, which is why it would be perfect to put it in the plug-in settings GUI.

**Comment by Saiyato** [comment]
Makes sense! Will check if I can easily incorporate that ;)
