### ISSUE TITLE
how to upgrade

### ISSUE THREAD

**Issue by karba78** [Saiyato/volumio-snapcast-plugin#38]
Hello
as you are pulling the last release of snapcast in your plugin
whats the process to upgrade your plugin and snapcast
especially now that the upload plugin function has been removed from volumio
thks

**Comment by Saiyato** [comment]
This has not yet been provisioned for

**Comment by karba78** [comment]
Ok Thank you 😊

Sent from Mail for Windows 10

**Comment by Saiyato** [comment]
Still not ready, not sure if Volumio has a nice trick for that.
