### ISSUE TITLE
Volumio Snapcast-> Spotify and radios

### ISSUE THREAD

**Issue by atze09** [Saiyato/volumio-snapcast-plugin#43]
Hello Saiyato,

First of all thanks for your amazing work regarding this awesome plugin!

As a background I had a running setup with manual installed snapcast server and client V0.11 and librespot. Currently I am facing the problem that I cannot get an output via the Spotify “stream” with VolSpotConnect2 nor librespot (standalone).
My volumio version is 2.201 and I have installed your plugin (server and client v0.13 and then the volspotplugin2).
The volspotplugin is working in standalone (I can connect with Spotify and play music).

`cat /data/plugins/music_service/volspotconnect2/startconnect.sh`
gives me
`./librespot -b 320  -c /tmp   --name 'wohnzimmer' --backend alsa --device plughw:1 --disable-audio-cache --initial-volume 33`

I have manually changed to pipe and /tmp/spotififo but after every restart it goes back to alsa and plughw:1.

What is the exact settings of volumio and your plugin to get all that working?
When i play internet radio this only works after a restart later there appear mpd problems.
How can i solve that?

My goal is to get volumio/Spotify/Airplay (Shairport sync running with snapcast.

Where is my failure?
Hope you can help me to get it running again.
Thank you in advance.

Best regards,
Dominik

**Comment by Saiyato** [comment]
Hi Dominik,

You have manually installed the snapcast components as I understand, but have you installed this plugin? I've just update the volspotconnect2 implementation sed, so that should work now.

If you manually update files, those change will be lost after a reboot. If you use the plugin and walkthrough, the changes are persistent. You can open the index.js file to see what I'm changing.

Why would you want to manually edit the files and not install the plugin?

**Comment by atze09** [comment]
Hello Saiyato,

Thank for your reply.
I had a manual solution before you released your snapcast plugin.
That's why i wanted to change this to your UI plugin, to easily edit.
I read in the other issue that you have changed the spotify section in your plugin.
I will a have a try of the new version and give a feedback here.

**Comment by atze09** [comment]
I had success in installing snapcast plugin and Volspotconnect2 (needed to reinstall volspotconnect).
Now it is working but the music is like pitched. sounds faster.
Maybe you can help me with thiss issue?

**Comment by Saiyato** [comment]
Hi Dominik,

Sounds like you need to play with the sampling rate for the implementation. This has happened to others too. I'm not at home this week, so can't link you to the previous issue. But you can find it in the resolved issues.

Cheers
