### ISSUE TITLE
Volspotconnect2 +  Snapcast

### ISSUE THREAD

**Issue by andrewj15** [Saiyato/volumio-snapcast-plugin#44]
Hi, I have updated my volspotconnect2 as my old version was no longer working. I installed the 20th march release from volumio. At this point I have also updated to your latest snapcast plugin. 

I am able to get web radio /local files working with snapcast. However when i patch the server for spotify and then save the volspotconnect2 plugin again,  the Server disappears as a playback option from spotify connect. 

I have tried saving the volspotconnect2 plugin multiple times as well as saving the snapcast server settings and rebooting the device, all with no luck. 

Has there been some recent changes to the volspotconnect2 plugin that are stopping it from working or is it user error on my part?

Thanks

Andrew

**Comment by orderoftheflame** [comment]
I've the same problem I'm afraid, though this is my first venture into using the snapcast plugin today. So this could just be my configuration.

I can get three devices synchronised fine listening to the web radio, but as soon as I start trying to enable volspotconnect2 it all breaks for me, and I can't even see the server as a spotify connect. Volspotconnect2 seems to working fine until I try to configure it in the snapcast settings.

Other than the spotify settings all of my snapcast config is default apart from selecting an different soundcard on the servers snapcast client, but nothing I seem to do with the spotify settings seems to work.

**Comment by atze09** [comment]
I have the same problem, maybe anyone can help us.

**Comment by Saiyato** [comment]
I'll try to look into this this weekend, but I can't promise anything
