### ISSUE TITLE
Can't get multiroom synchronized play to work

### ISSUE THREAD

**Issue by wtrdk** [Saiyato/volumio-snapcast-plugin#45]
Hi,

I have 2 rapsberry pi 3 with the latest volumio image. I've also installed this plugin and followed the instructions, but I can't play them in sync.
I can stream from my iOs Spotify client to either one of them, but not in sync. 
Is there an easy, minimal setup instruction to get this to work?

Thanks!

**Comment by Saiyato** [comment]
I can confirm this if you are using volspotconnect 1.7.5. Are you, or are you using another implementation?

**Comment by wtrdk** [comment]
I don't use a spotify connect plugin. Just spotify on my phone with airplay to volumio.

**Comment by Saiyato** [comment]
Oh that's a different problem entirely... shairplay is not yet supported in this plugin, I think I need to reroute alsa still.

**Comment by Saiyato** [comment]
I just found out that shairport-sync was not built with pipe output on current Volumio builds, so this is not possible at the moment.

**Comment by Saiyato** [comment]
AirPlay is still under construction, but will only be added to the new plugin(s):
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
