### ISSUE TITLE
Music sped up when playing

### ISSUE THREAD

**Issue by orderoftheflame** [Saiyato/volumio-snapcast-plugin#46]
My setup is one Pi Zero W as the server (and a client), streaming to a couple of other Pi Zero W clients.

When I play music, across them all, it's perfectly in sync, but always appears to be slightly sped up on all of them. It's subtle but noticeable. I presume this is just part of the sync process.

Does the master (or clients) have to be a more powerful Pi than a Pi Zero? Or could it possibly be that my wireless network isn't quite up to scratch for multi room audio? I haven't been able to test wired connections due to the Pi Zeros not supporting it.

Could it be something else causing this issue?

**Comment by Saiyato** [comment]
Hi there,

You should fiddle with the sampling rates, this 'sped up' sound is caused by resampling I think.
It's quite possibly the difference between 44.1KHz and 48KHz, let me know how that works out for you.

**Comment by orderoftheflame** [comment]
Ah, thanks for the info. :)

I'll give that a go when I can get a chance too. Might be a week or so though.
On 01/06/2018 11:09:43, EWRGroeneveld <notifications@github.com> wrote:
Hi there,
You should fiddle with the sampling rates, this 'sped up' sound is caused by resampling I think.
It's quite possibly the difference between 44.1KHz and 48KHz, let me know how that works out for you.

**Comment by orderoftheflame** [comment]
Hi @Saiyato,

Changing the sampling worked instantly, it's playing perfect now!

Thanks for the help, and thanks for a great plugin. :)

**Comment by Saiyato** [comment]
Awesome, thanks for the feedback! :)
