### ISSUE TITLE
Spotify settings - Pitched songs

### ISSUE THREAD

**Issue by GiDiPa** [Saiyato/volumio-snapcast-plugin#47]
Hi! I'm trying to setup with your plugin(great job!), and I've almost done. My setup is:
1 RPI 3 as server and client at same time;
2 RPI B+ as only clients;

Setup without Spotify works almost well. But I can hear two problems when I switch, with android app, in Spotify playback. 
1- The song has some lag before starts to play(if server plays songs too).
2- Songs are out of tone(pitch up) when server is playing with the others clients. If server work as it is, without activate client mode, songs plays as usual.

Thanks in advance!

**Comment by Saiyato** [comment]
Yes, this is correct, it has to do with another way of enabling playback for Spotify.
I will update the defaults tomorrow... in the meantime, change all sampling rates to 44100Hz, that'll solve your problem ;)

I'm still looking for a way to resample to 48kHz... to be continued ;)

**Comment by Saiyato** [comment]
The above was aimed at question two, the first one is caused by the server not playing through snapcast. I don't think it's really possible to play out of sync if all players grab the fifo stream.

In any way, my new commit should sort thing out more neatly :)
