### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by miloit** [Saiyato/volumio-snapcast-plugin#49]
these are my steps

volumio@volumio:~/volumio-snapcast-plugin-master$ rm volumio-snapcast-plugin.zip
volumio@volumio:~/volumio-snapcast-plugin-master$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
/bin/rm: cannot remove 'package-lock.json': No such file or directory
Error installing node modules: Error: Command failed: /bin/rm package-lock.json
/bin/rm: cannot remove 'package-lock.json': No such file or directory

/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/snapcast.zip
/bin/mv: cannot stat '*.zip': No such file or directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:680:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:741:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
volumio@volumio:~/volumio-snapcast-plugin-master$

**Comment by Saiyato** [comment]
What version of Volumio and on what platform did you try this on?
Can you try to run npm i first, if needed with sudo?

**Comment by miloit** [comment]
It raspberry zero w with volumio2 2.44

**Comment by layereight** [comment]
Same problem here. Raspberry Pi Zero W with volumio 2.444. Doing `npm i` prior to `volumio plugin install` did the trick. No `sudo` necessary.

@Saiyato Maybe you want to add this to the README. And btw, great work. Loving it. Listening to in-sync multi-room music right now. :-)

**Comment by Saiyato** [comment]
Awesome, thanks for the update! :)

I was asked to delete the installation instructions from the repo by Volumio, I've created a PR so it can be installed from the store instead. This will solve all installation issues.

**Comment by miloit** [comment]
where can i find it? It is not listed in the plugins

**Comment by Saiyato** [comment]
here: https://github.com/volumio/volumio-plugins/pull/242

**Comment by miloit** [comment]
So I need to wait until pull request is approved?

**Comment by Saiyato** [comment]
Basically yes, or get your hands dirty and install manually, but that'll require some knowledge about linux and installing/compiling stuff.
