### ISSUE TITLE
Pine64 - Lot's of noise, almost no music sound

### ISSUE THREAD

**Issue by ThaDaVos** [Saiyato/volumio-snapcast-plugin#53]
I've got the plugin running great on two raspberry pi 2b's but when running it on my Pine64 there's lot's of static noise and almost no music.

Tried the Pine64 without the plugin and it's fine, but with the plugin, as server + client or client only there's more static noise than music so completely unusable.

Do you know any fixes?

**Comment by Saiyato** [comment]
What music source are you using? Playback from MPD?
Did you change anything in the resampling section?

**Comment by ThaDaVos** [comment]
Using the same settings as my Pi's - currently just webradio (RTV Drenthe)

**Comment by ThaDaVos** [comment]
Fixed it by using the Sound Blaster Play! 3 USB Soundcard - so probably a driver issue

**Comment by Saiyato** [comment]
Awesome, thanks for the feedback! :)

**Comment by Davdav05** [comment]
Same issue here...
Not sure why this is marked as closed since it wasn't resolved. OP just used a different (external) Soundcard to make it work.

**Comment by Saiyato** [comment]
Hi @Davdav05 ,

Because the OP mentioned that it probably was a driver issue.

Can you get it to work without the plugin? I.e. by installing SnapCast yourself? The question is whether or not the _plugin_ is causing it, snapcast itself or some other environmental setting.

Please advise.

**Comment by Davdav05** [comment]
Gotcha. Actually I think it's an issue with Volumio itself and not snapcast. I was able to reproduce the issue when using volumio. The 'volume normalization' option causes it, as well as the spotify plugin on mine...

**Comment by Saiyato** [comment]
Which Spotify plugin are you referring to in this case; spop or volspotconnect? Because volspotconnect1 uses resampling, which is also known to cause noise, I dont think the librespot imp has resampling enabled right now.

This info might help others :)

**Comment by Davdav05** [comment]
I was referring to the Connect plugin

**Comment by Saiyato** [comment]
If you are using volspotconnect1, try disabling resampling, else you should read into librespot and see if you can find anything related to resampling.
