### ISSUE TITLE
Directory in step 3 does not exist

### ISSUE THREAD

**Issue by mabushey** [Saiyato/volumio-snapcast-plugin#54]
3. CD into volumio-snapcast-plugin directory

root@music1:/# find / -type d -name "volumio-snapcast-plugin"

Not coming up with anything... Do I need to create this dir, and if so, where? If not, please provide the full path.

**Comment by Saiyato** [comment]
This depends on your unzipping command, I always create a dir into which I unzip to keep the home dir clean and proper.

**Comment by Saiyato** [comment]
Any news on the above?

**Comment by Saiyato** [comment]
It should be in the store soon, so no manual installation is required anymore
