### ISSUE TITLE
Plugin Apparently Incompatible with latest Volumio releases (2.457+)

### ISSUE THREAD

**Issue by sebcoh** [Saiyato/volumio-snapcast-plugin#56]
The snapcast plugin apparently doesn't work with at least the two latest Volumio2 versions (2.457, 2.502). 
A client still finds the host but music is never played back. Workarounds unknown despite a lot of trial-and-error.

**Comment by Saiyato** [comment]
Hi there,

I'm going to need a little more info than 'doesn't work' ;)
What platform are you using? What music sources have you been using, what are their configs and what does the machine log (e.g. in the journal)?

Please advise.

**Comment by sebcoh** [comment]
Hey! Sorry about the lack of details. The thing is, I don't see any error messages, it simply does not play anything on the client when before the Volumio update it did.

This is the log from the server: http://logs.volumio.org/volumio/huneAh5.html
This is from the client: http://logs.volumio.org/volumio/pXTmpio.html

Looks like each second, the server spits out the following two logs (the client too, but not as often):

Nov 12 19:53:13 raspi snapclient[4380]: Exception in Controller::worker(): connect: Connection refused
Nov 12 19:53:13 raspi snapclient[4380]: Error in socket shutdown: Transport endpoint is not connected

**Comment by Saiyato** [comment]
Hi there,

The server probably also has the client enabled, the client applications are complaining they can't connect to the server instance. This looks like a connectivity issue, not so much the plugin (which only enables you to install and configure the two components). 

Did you try to reconfigure the plugin? Because I'm pretty sure that upgrading Volumio can change you mpd config etc.

**Comment by sebcoh** [comment]
Yeah I tried all settings that I could find to no avail. The client can find the server (i.e. the server can be selected in the SnapClient settings) but the connection is still refused.
I will try to reinstall volumio and the plugin and report back.

**Comment by sebcoh** [comment]
Okay it appears to work correctly now, no idea what went wrong before. Thanks for your great help!

**Comment by Saiyato** [comment]
I think some of the necessary config files were overwritten in the upgrade procedure, this will break functionality unfortunately. But I'm glad it's working again now.
