### ISSUE TITLE
WebUI does not show for Settings

### ISSUE THREAD

**Issue by JoakimLindbom** [Saiyato/volumio-snapcast-plugin#57]
I believe issue #17 has resurfaced. I have 3 RPi:s running Volumio. On the one with Hifiberry DAC Plus the UI shows up fine, but on the one with Hifiberry Amp+ it does not.
In /data/configuration/audio_interface/alsa_controller/config.json it's shown as:
```
...
"outputdevicename": {
"type": "string",
"value": "HiFiBerry Amp"
}

```
Not as Amp+ as I would expect.

In the log I can see:
amixer: Mixer attach hw:1 error: Invalid argument
Which can be explained by looking at asound.conf:
cat /etc/asound.conf
```
        #SNAPCAST
        pcm.!snapcast {
                type plug
                slave.pcm snapConverter
        }

        pcm.snapConverter {


        pcm.writeFile {
                type file
                slave.pcm null
                file "/tmp/snapfifo"
                format "raw"
        }
        #ENDOFSNAPCAST

```

I'm running Volumio 2.513, SnapCast 2.3.3 and Spotify Connect2 0.7.4

Logs at: http://logs.volumio.org/volumio/yJIJ1t5.html

**Comment by Saiyato** [comment]
This looks like a messed up asound config indeed, re-saving the settings should overwrite everything between the hashes. Can you try that please?

**Comment by Saiyato** [comment]
I found the problem, the latest commits should not have this problem anymore. Somewhere along the road the install.sh file got corrupted. Mea culpa
