### ISSUE TITLE
volume control settings

### ISSUE THREAD

**Issue by dddesign** [Saiyato/volumio-snapcast-plugin#63]
I do not have any clients in the dropdown menu for selecting a snapclient to control volume for. I have multiple snapclients running on different devices. if a local snapclient is running the volume control is working for this client (even if it's not listed in the dropdown)

what could be the problem that they don't show up?

**Comment by Saiyato** [comment]
Hi @dddesign , did you connect the clients to the server already? Because they need to be known upfront.

**Comment by dddesign** [comment]
They are connected. I see all of them with the android app ( https://github.com/badaix/snapdroid).

**Comment by cschuhen** [comment]
I have the same issue. I have multiple clients connected/working. Only way to adjust volume is with android app mentioned above.

**Comment by X-eno** [comment]
I can confirm this too.
The only option to select the client is: "Disable volume update"
Nothing else to select.

The Dropdowns from "client to link to the specified stream" and "select the stream...." are complete empty.

![VoluSnap](https://user-images.githubusercontent.com/19558838/105555478-c4a26d00-5d09-11eb-9b98-e3747ff55895.JPG)

**Comment by Saiyato** [comment]
Somehow the settings in Volumio 2 changed over time, this functionality was also a bit flaky to begin with so I disabled it.

You can find the new plugins (Volumio 3 ready) here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
