### ISSUE TITLE
On the RP with SnapCast Server + Client: Echo (2 sounds) on the HDMI output 

### ISSUE THREAD

**Issue by boulonCH** [Saiyato/volumio-snapcast-plugin#65]
I have built a multiroom system based on SnapCast V2.4.2 with Volumio V2.598 on 2 Raspberry Pi (RP) model 3B and 1 smartphone with the SnapCast app V0.14.0.14
1 RP3 (wired Ethernet) with SnapCast Server + Client On with HDMI output (I2S DAC Off)
1 RP3 (wifi Ethernet) with SnapCast Client On only with a HifiBerry DAC as audio output
1 Smartphone (wifi Ethernet)  with the earphone as audio output

From the SnapCast App on the smartphone I can control all the 3 SnapCast Clients (switch Volume on or off + volume level). Everythings works well except on the RP3 with the SnapCast Server + Client.
On this RP3 with the HDMI output the sound goes out with an echo. The echo is made of the sound going directly to the HDMI output + the sound going to the HDMI output through the SnapCast system with a delay.
If I switch off the sound of the RP3 with the SnapCast Server + Client from the app. I have no more echo but I get a delay between the sound going out from the HDMI output and the 2 other outputs (Hifiberry DAC + earphone) as the sound going to the HDMI output goes no more through the SnapCast server but only directly.

From a configuration point of view how I can proprely solve this problem to have no more delay? How can I switch off the sound going directly to the HDMI output ?

An other solution I guess would be to split the RP that act as a SnapCast Server + Client into 2 RP: one RP with the SnapCast Server only and the 2nd RP with the SnapCast Client only, but it is not an optimum solution from a hardware point of view !

Thank you very much in advance for your response

**Comment by Saiyato** [comment]
Hi there,

What music source are you using and what settings did you change after installing the plugin?
Installation should take care of disabling direct output (causing the echo), somehow it either didn't work OR you changed sound settings and re-enabled direct sound output (because Volumio will overwrite the config the plugin writes).

**Comment by boulonCH** [comment]
Hello,
Thank you for your quick replay.
In this case I was using Webradio from Volumio's list. I did also try with the BubbleUpnp app (smartphone) and get the same effect.
I did not change any settings after installing the SnapCast plugin. To be sure, I remove the plugin and install it again without changing Volumio settings after and I get the same echo effect.
By the way, after reinstalling the SnapCast plugin I saved the SnapCast Server configuration and get an error (red message):
-Script executed (green message)
-Restart failed (red message)
  Restarting snapserver failed with error: Error: Command failed: /usr/bin/sudo/bin/systemctl restart snapserver Job for snapserver.service failed. See…
-Successful Push (green message)
I saved it a 2nd time and get no error message !

By the way, informations from the SnapCast plugin:
-SnapCast Settings: 
  Soundcard To Use for Playback: 
     Omit Soundcard parameter
-Current Volumio Sound Config
  Output device: 
    Audio Jack !!!
Hope it will help.

**Comment by Saiyato** [comment]
I just retested this, but I'm not getting any echoes, can you retest please? I've downloaded the latest image and installed the plugin from the store, both my 3B and 3B+ work perfectly.

**Comment by boulonCH** [comment]
I just tried back from holidays. I get the same error as #67 (snapcast-server down although activated in GUI).
Tested on RP3+ volumio v2.657 with snapcast 2.4.3 (0.16.0).

![Screenshot_20191025-142132_Opera](https://user-images.githubusercontent.com/33683939/67572939-85b4ee80-f737-11e9-9b89-6e581e32cb25.jpg)

**Comment by tolexy** [comment]
I am getting the same first red banner error in the boulonCH's post: snapsever.service is masked. Restarting the service does not help. I am however (usually) able to update the also configs and all the other configs. Oddly, I have the client running on one server, and at one point the client was running and it could see the snapcast server on the main volumio pi, but all playback was still independent. 

Rpi 4 is the snap server, rpi3 is the client (to expand to an rpi2 adn another rpi3 eventually)

**Comment by Saiyato** [comment]
Hi all,

The masked service is fixed now, but a new problem arose since the latest version of Volumio (see #68). We're not there yet ;)

**Comment by Saiyato** [comment]
Most issues have been resolved, but the owner of /etc changed, this is causing problems for asound.conf

**Comment by boulonCH** [comment]
Hello,
it is now working perfectly - no more echo- with Volumio v2.279 + SnapCast v2.5.1. Thank you very much for all. What was the problem ?
Regards

**Comment by Saiyato** [comment]
Hi,

Good to hear, the problem was probably a hanging mpd.conf setting.
Enjoy!
