### ISSUE TITLE
snapcast-server down although activated in GUI

### ISSUE THREAD

**Issue by bbernhard** [Saiyato/volumio-snapcast-plugin#67]
I just installed the `volumio-snapcast-plugin` on a freshly deployed Volumio (version: latest version) and for some reason the `snapcast-server` wasn't starting although the plugin was activated and the snapcast server was enabled the UI. 

`systemctl status snapserver` showed the following output: 

```Oct 10 18:10:41 wohnzimmer systemd[1]: Unit snapserver.service entered failed state.
Oct 10 18:10:42 wohnzimmer systemd[1]: snapserver.service holdoff time over, scheduling restart.
Oct 10 18:10:42 wohnzimmer systemd[1]: Stopping Snapcast server...
Oct 10 18:10:42 wohnzimmer systemd[1]: Starting Snapcast server...
Oct 10 18:10:42 wohnzimmer systemd[1]: snapserver.service start request repeated too quickly, refusing to start.
Oct 10 18:10:42 wohnzimmer systemd[1]: Failed to start Snapcast server.
Oct 10 18:10:42 wohnzimmer systemd[1]: Unit snapserver.service entered failed state.
```

I also tried rebooting Volumio, but unfortunately that didn't solve the problem. The only thing that worked for me, was executing

`systemctl daemon-reload`

on the commandline. After that I was able to start the `snapcast-server` with: 

`systemctl start snapserver`

After I've manually fixed the problem, everything was working fine (the system also survived a reboot ;)). 

Not sure if this is already known, so I thought I'd create a ticket for that.

**Comment by camg70** [comment]
I dp have same problema , but mitigation daemon-reload does not solve.  I have  message: UNIT snapserver.service is masked.

**Comment by camg70** [comment]
I believe plugin is downloading latest release of snapcast that has been updated
to 0.16.0....   and is not compatible

**Comment by Saiyato** [comment]
I've seen it happen now, working on a fix, don't know where this is coming from tbh

**Comment by camg70** [comment]
I Forced Plugin to install old version 0.15.0 from  snapcast and it's ok.
Just for notice : Plugin Volspotconnet2  seems to be also modified  not working with snapcast, will check later ant return with news, thanks Saiyato...

**Comment by tolexy** [comment]
Firstly, thanks for all the work on this! I wanted to second all the comments above. Multiroom works fine, settings all seem correct, but even though plugin is enabled in volumio, the snapclient and snapserver cannot start. The service is masked. Unmasking removes the symlink and then the file is not found and cannot even uninstall the plugin from within volumio at that point. 

WIll try the old version 0.15.0 perhaps later.

**Comment by tolexy** [comment]
for what it's worth, i did a factory reset on the volumio rpi. Upgraded to newest version of volumio 2.657 and installed version 0.15 only. Unfortunately I still get this message from the snapserver pi box
![image](https://user-images.githubusercontent.com/25507684/67599941-19d68400-f73f-11e9-96dc-320144dcda68.png)

snapclient pi (running volumio 2.657 and snapcast plugin 0.16) is working it seems...
![image](https://user-images.githubusercontent.com/25507684/67600039-4c807c80-f73f-11e9-9639-cb615318cd09.png)

This may be a bit naive, but if and when snapserver is started, when I hit play on the main server, the client should start playing immediately yes?

**Comment by mountwebs** [comment]
Same issue here.

> I Forced Plugin to install old version 0.15.0 from snapcast and it's ok.

camg70: It would be great if you could share how this is done.

**Comment by camg70** [comment]
I did a manual installation of plugin "git clone."
there is a file called install.sh or start....sh that downloads de last
version os snapcast.. edit it,,,a sequence of IF...depending on kind of
processor you use.
delete de line that pull the version .
instead, you should download directly from gitub older version of snapcast
to same expected folder
than, when you run volumio plugin install, the installation will void
download and will install older version.

I can make it more clear if you need




mountwebs <notifications@github.com> escreveu no dia sábado, 26/10/2019
à(s) 23:00:
