### ISSUE TITLE
Get Spotify connect working

### ISSUE THREAD

**Issue by murmelbahn** [Saiyato/volumio-snapcast-plugin#70]
Hi all,
I've tried several hours to archieve the following:
I want to start a song via Spotify IOS App to play on 2 Volumio devices.
I have one Rapsi 3 with DAC and one Pi Zero W with a DAC.
So how does this work? 
Should I see a Spotify Connect target called "Multiroom" to let the music on all devices play? Should I send the music to the snapcast server target via Spotify connect and the client on the other Pi will play the same?
I've tried several settings to archieve this but honestly I don't know what to do next. Can someone give me a hint how to have muliroom music via Spotify connect?
Thanks in advance!

**Comment by Saiyato** [comment]
Hi,

You should select the Spotify integration you are using in the plugin, then refresh the page (I haven't been able to automate this). Navigate back to the plugin, patch the Spotify config (just click the patch button) and reboot the system. You only need to do this once, after that just select the Volumio player in the Spotify app and listen to the music ;)

**Comment by dddesign** [comment]
I also have problems to get volspotconnect2 working.
I use volumio-snapcast version 2.5.1 and Volumio Spotify Connect 2 version 0.9.9
after setting integration of spotify in snapcast, reloading plugin page, patching spotify config (as it mention above and in the readme) and restarting volumio is not showing up in spotify player (e.g. webplayer). before activating snapcast I tested spotify connect2 plugin alone, it was working.
any tips how to debug it? thanks

**Comment by dddesign** [comment]
I change the settings in SpotifyConnect2 to NOT use Multi-User Device and set my device number as username with my password. with this settings Volumio showed up in Spotify Web Player.

**Comment by dddesign** [comment]
update:
after enabling multi-user device again and restarting volumio I can use spotify on volumio with any premium device (in my case: I have a familiy account with diffrent users)
