### ISSUE TITLE
can't get latest releases (Volumio, and Snapcast plugin) to work on remote device (solved with last volumio build)

### ISSUE THREAD

**Issue by karba78** [Saiyato/volumio-snapcast-plugin#71]
config
- 1 volumio 2.692 with snapcast plugin installed (server and client) manually from GitHub. from here
https://github.com/Saiyato/volumio-snapcast-plugin/blob/master/volumio-snapcast-plugin.zip
built end of december
Running on a RPI4 with IQAudio Amp
This piece is working well the music plays, i assume the local client is reading from the local server

- 1 volumio 2.692 with snapcast plugin client (latest too) and IQAudio DAC Card
Device plays well local music, but does not play from snapcast server.
Snapcast server is visible in snapcast client config.

- 1 volumio 2.692 with snapcast plugin client (latest too) and HifiBerry DAC Card
Device plays well local music, but does not play from snapcast server.
Snapcast server is visible in snapcast client config.

- 1 volumio 2.692 with snapcast plugin client (latest too) and IQaudio DAC and Amp Card
Device plays well local music, but does not play from snapcast server.
Snapcast server is visible in snapcast client config.

Net Net no remote client is playing server stream...
one new thing; the volumio client page section "Current Volumio Sound Config"  shows "no card match"
another new thing; the mixer type value is not showing hardware type anymore

seems to be linked to hardware mixer dissapering with latest release :( see here
https://forum.volumio.org/after-update-657-volume-control-t13107-40.html

any tip on how to debug
thks

**Comment by karba78** [comment]
upgrade today to 2.698 of Volumio, and installed latest plugin manually 2.4.5
still no luck on remote devices; no sound from snapcast server; devices are functional with shairport and local music.
there is an error msg when saving config on snapcast server but can't see it its too fast
can you help point me to where i could find logs to debut
thks

**Comment by karba78** [comment]
manage to make it work after starting manually snapcast server with systemctl
seems the plugin install/setup can't succeed starting it

**Comment by karba78** [comment]
found the issue in mpd.conf.
the plugin config script are not removing the also audio output, but just appending the fifo one
had to manually comment the alsa section

# Volumio MPD Configuration File

# Files and directories #######################################################
music_directory         "/var/lib/mpd/music"
playlist_directory              "/var/lib/mpd/playlists"
db_file                 "/var/lib/mpd/tag_cache"
log_file                        "/var/log/mpd.log"
#pid_file                       "/var/run/mpd/pid"
#state_file                     "/var/lib/mpd/state"
#sticker_file                   "/var/lib/mpd/sticker.sql"
###############################################################################

# General music daemon options ################################################
user                            "mpd"
group                          "audio"
bind_to_address         "any"
#port                           "6600"
#log_level                      "default"
gapless_mp3_playback                    "no"
#save_absolute_paths_in_playlists       "no"
#metadata_to_use        "artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update    "yes"
#auto_update_depth "3"
###############################################################################
# Symbolic link behavior ######################################################
follow_outside_symlinks "yes"
follow_inside_symlinks          "yes"
###############################################################################
# Input #######################################################################
#
input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}
###############################################################################

# Decoder ################################################################





###############################################################################

# Audio Output ################################################################

resampler {
                plugin "soxr"
                quality "high"
                threads "1"
}

audio_output {
                type            "alsa"
                enabled         "no"
                name            "alsa"
                device          "hw:1,0"
                dop                     "no"




}





audio_output {
    type            "fifo"
    enabled         "yes"
    name            "multiroom"
    path            "/tmp/snapfifo"
    format          "44100:16:2"
}

#replaygain                     "album"
#replaygain_preamp              "0"
volume_normalization            "no"
###############################################################################

# MPD Internal Buffering ######################################################
audio_buffer_size               "2048"
buffer_before_play              "10%"
###############################################################################


# Resource Limitations ########################################################
#connection_timeout             "60"
max_connections                 "20"
max_playlist_length             "81920"
max_command_list_size           "81920"
max_output_buffer_size          "81920"
###############################################################################

# Character Encoding ##########################################################
filesystem_charset              "UTF-8"
id3v1_encoding                  "UTF-8"
###############################################################################

**Comment by Saiyato** [comment]
I will try to get the plugin updated as well, the latest version will work on Jessie again
