### ISSUE TITLE
No more audio from snapcastserver

### ISSUE THREAD

**Issue by kurtwerbrouck** [Saiyato/volumio-snapcast-plugin#72]
Hello
I installed on 2 rpi-s volumio with the snapcast plugin. One is running the server the other as client. After a few houres - around 2h 2h30 the server stops sending the stream to the client. A reboot of the snapcast server , the system runs again for a few houres, and again the server stops.

Any suggestion what i can do to fix the issue? 

I need to hookup 24 raspi volumio Snapcast client on 1 snapcastserver.

Thanks

**Comment by karba78** [comment]
think i found the issue
somehow volume is rewriting mpd.conf and the fifo output gets unvalidated.
i have commented the hw section see below, to let the fifo section active but at every reboot volumio erase my changes
any idea on how to avoid this


#audio_output {
#               type            "alsa"
#               name            "alsa"
#               device          "hw:1,0"
#               dop             "no"
#}

audio_output {
    type            "fifo"
    enabled         "yes"
    name            "multiroom"
    path            "/tmp/snapfifo"
    format          "44100:16:2"
}

**Comment by kurtwerbrouck** [comment]
After 2h or so, the volumio is rewriting the config file?

**Comment by karba78** [comment]
I am not sure about the timing,,,, just made the change in the mpd.conf.tmpl file, will see if I can make it persist in not changing, will keep you posted

**Comment by karba78** [comment]
worked today, rebooted and kept my mpd.conf clean can now stream via snapcast spotify source as well as local/remote files source

**Comment by karba78** [comment]
stopped working again, 
I got this working this week by commenting the hw section in mpd.conf, but it did not last. my files db got corrupted and mpd would not rebuild it, had to reset and cant get it to work again.
I am posting my files below if @Saiyato has a couple of minutes to look at it, or someone else who managed to get it working.. would be highly appreciated
Volumio MPD Configuration File
Files and directories
music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/tag_cache"
log_file "/var/log/mpd.log"
#pid_file "/var/run/mpd/pid"
#state_file "/var/lib/mpd/state"
#sticker_file "/var/lib/mpd/sticker.sql"
###############################################################################
General music daemon options
user "mpd"
group "audio"
bind_to_address "any"
#port "6600"
#log_level "default"
gapless_mp3_playback "no"
#save_absolute_paths_in_playlists "no"
#metadata_to_use "artist,album,title,track,name,genre,date,composer,performer,disc"
auto_update "yes"
#auto_update_depth "3"
###############################################################################
Symbolic link behavior
follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
###############################################################################
Input

input {
plugin "curl"
proxy "proxy.isp.com:8080"
proxy_user "user"
proxy_password "password"
}
###############################################################################
Decoder
###############################################################################
Audio Output
resampler {
plugin "soxr"
quality "high"
threads "1"
}
audio_output {
type "alsa"
enabled "no"
name "alsa"
device "hw:1,0"
dop "no"
}
audio_output {
type "fifo"
enabled "yes"
name "multiroom"
path "/tmp/snapfifo"
format "44100:16:2"
}
#replaygain "album"
#replaygain_preamp "0"
volume_normalization "no"
###############################################################################
MPD Internal Buffering
audio_buffer_size "2048"
buffer_before_play "10%"
###############################################################################
Resource Limitations
#connection_timeout "60"
max_connections "20"
max_playlist_length "81920"
max_command_list_size "81920"
max_output_buffer_size "81920"
###############################################################################
Character Encoding
filesystem_charset "UTF-8"
id3v1_encoding "UTF-8"
###############################################################################
---------------spopd file------------------------------
[spop]
spotify_username = yyyy
spotify_password = xxxx
high_bitrate = true
refresh_token = none
audio_output = sox
pretty_json = true
search_results = 50
cache_path =/run/shm
[sox]
output_type = raw
output_name = /tmp/snapfifo
-------------snapserver config files-------------------------
USER_OPTS="--user snapserver:snapserver"
SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=VOLUMIO-MPD&mode=read&sampleformat=44100:16:2 "
--------------snapserver client files--------------
USER_OPTS="--user snapclient:audio"
SNAPCLIENT_OPTS="-d -h 192.168.0.242 -s IQaudIODAC "
-------------------asound file-----------------------------
#SNAPCAST
pcm.!snapcast {
type plug
slave.pcm snapConverter
}
pcm.writeFile {
type file
slave.pcm null
file "/tmp/snapfifo"
format "raw"
}
#ENDOFSNAPCAST

**Comment by karba78** [comment]
I finally got it working.. 
I think I understood there is no way to direct spop to alsa and then to fifo.
the system comes preconfigured with mpd to also to fifo
when installing spop, spop directs to alsa

the only way I found to make it work is amend  spopd.conf to output to fifo, and change mpd.conf to output to fifo directly instead of via alsa
would have been more elegant to have spop and mpd to alsa and then alsa to fifo but could not make that work

files below, lets see if database holds this time or get corrupted again

----- spopd.conf-----------
[spop]
spotify_username = xxxxx
spotify_password = yyyy
high_bitrate = true
refresh_token = undefined
audio_output = sox
pretty_json = true
search_results = 50
cache_path =/run/shm

[sox]
#output_type = raw
#output_name = /tmp/snapfifo
output_type = raw
output_name = /tmp/snapfifo

---mpd output section ---- (also amended the .tmpl file to avoid mpd.conf to be reset at each startup----
# Audio Output ################################################################
resampler {
                plugin "soxr"
                quality "high"
                threads "1"
}

#audio_output {
#               type            "alsa"
#               name            "alsa"
#               device          "hw:1,0"
#               dop                     "no"
#}


audio_output {
    type            "fifo"
    enabled         "yes"
    name            "multiroom"
    path            "/tmp/snapfifo"
    format          "44100:16:2"
}

#replaygain                     "album"
#replaygain_preamp              "0"
volume_normalization            "no"
###############################################################################

**Comment by Saiyato** [comment]
Hi @karba78 

Editing the Spotify integration part, refreshing the page and returning to the plugin settings will enable you to patch the spop template file. This would make the change persistent. If you simply edit the spopd.conf file, it will get overwritten on EACH reboot/restart of the plugin.

@kurtwerbrouck can you provide some log on your behaviour? I've played for several hours this weekend without any issues. Note that I was using Spotify (volspotconnect2). Please advise

**Comment by kurtwerbrouck** [comment]
Hi saiyato

I am travelling for the moment, i can perform te test at the end of march.
I used a web radio stream www.icecast.vrtcdn.be/stubru-high.mp3 during all my testing


Kurt
