### ISSUE TITLE
Server does not start Unit snapserver.service is masked

### ISSUE THREAD

**Issue by HJKLMN** [Saiyato/volumio-snapcast-plugin#73]
Hi, 

Wanted to start using Snapcast with my system. Could not get it working, because after installing (using the UI, when I enable it in the UI i get an error:
Failed to restart snapserver.service: Unit snapserver.service is masked.

Tried login in using ssh:

root@atelier:/home/volumio# systemctl unmask snapserver
Removed symlink /etc/systemd/system/snapserver.service.
root@atelier:/home/volumio# systemctl mask snapserver
Created symlink from /etc/systemd/system/snapserver.service to /dev/null.
root@atelier:/home/volumio# systemctl start snapserver                          Failed to start snapserver.service: Unit snapserver.service is masked.

**Comment by VieGie** [comment]
I remember getting this error message when I installed the plugin from the store. I think you won’t see this error when you install the latest release straight from Github. Somewhere, in one of the reported issues on the plugin on Github, I know Sayaito mentioned he solved this. That’s when I installed a new copy that worked.

**Comment by Saiyato** [comment]
Yes, the rights on the file system are subject to change, that is causing this behaviour. The latest is not showing this particular issue anymore. Will try to push to the store asap, but I'm running into other problems now.
