### ISSUE TITLE
Volspotconnect2 - multiroom not working

### ISSUE THREAD

**Issue by VieGie** [Saiyato/volumio-snapcast-plugin#74]
I have installed the lastest version of snapcast (addressing issue #60 and #61) and Volumio Spotify Connect 2 v0.9.9. When patching and saving the volspotconnect2 setup, volspotconnect2.tmpl does not get altered as expected. This is how my startconnect.sh looks like:
`#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwritten by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./vollibrespot -b 320 -c /tmp  \
                  --disable-audio-cache \
                  --name 'keuken' --initial-volume 80\
                  --device plughw:1   \
                  --mixer alsa \
                  --mixer-name 'Digital' --mixer-card 'hw:1'  \`

Mpd multiroom works currently. If I change the volspotconnect2.tmpl directly to contain "--backend pipe --device '/tmp/snapfifo'" Spotify multiroom works too, but at the sample rate of mpd (too fast). 

Where should I begin to look for pointers? All advise welcome!

**Comment by dgarciamontes** [comment]
I have exactly the same problem. I try your fix using --backend pipe --device '/tmp/snapfifo and it's working as you said, too fast.

Tomorrow I will continue to find the way. 

EDIT:
I'm looking into the source, this is it was supposed to change on template file:
### .
       else if (imp == "volspotconnect2")
	{
		self.replaceStringInFile("--device ${outdev}", "--backend pipe --device " + self.config.get('spotify_pipe') + " $\\{normalvolume\\} \\", "/data/plugins/music_service/volspotconnect2/volspotconnect2.tmpl");
		defer.resolve();
	}


Pipe
The pipe back-end requires very minimal setup provided you have an audio player which can accept and process the output correctly.

The pipe outputs the data as raw stereo 16bit 44.1KHz bytes. This is true for any bitrate (quality) setting.

All advise welcome!

**Comment by dgarciamontes** [comment]
I did some progress:

I see that snapclient is always connecting to the first stream pipe declared into the config file /etc/default/snapserver

Changing the order you have some result but it only inverse the problem and you can't stream music from MPD

We could have the same effect changing the template using /tmp/spotififo

I think I found a little error in the config:

"spotify_pipe": {
    "type": "string",
    "value": "/tmp/snapfifo"
  },

this one is not /tmp/spotififo ?

**Comment by VieGie** [comment]
Indeed, that’s where I got the ‘backend’ - config from. There must be a reason why the source doesn’t write the template, but I don’t how to check where it goes wrong.

Have you tested changing the configuration to /temp/spotififo? I will try to have a look at it this weekend.

**Comment by dgarciamontes** [comment]
> Indeed, that’s where I got the ‘backend’ - config from. There must be a reason why the source doesn’t write the template, but I don’t how to check where it goes wrong.
> 
> Have you tested changing the configuration to /temp/spotififo? I will try to have a look at it this weekend.

Yeah, I've tested and it's working for spotify.

**Comment by VieGie** [comment]
I mean, did it help changing the possible error to spotififo? Where did you find the statement about the Spotify_pipe? I found a similar one in the index.js of the Snapchat plugin and it seemed correct to me. It’s included in an of statement: if dedicated stream = spotififo, else snapfifo.

**Comment by Saiyato** [comment]
This one should be fixed now, but I'm running into permission problems, the owner of /etc/ has been changed to root (was volumio)

I did manage to patch index.js, installing from GitHub should solve that issue at least.

**Comment by dgarciamontes** [comment]
> This one should be fixed now, but I'm running into permission problems, the owner of /etc/ has been changed to root (was volumio)
> 
> I did manage to patch index.js, installing from GitHub should solve that issue at least.

Thank you Saiyato, I will try your last patch as soon I have some spare time!

**Comment by VieGie** [comment]
Hi Saiyato, thank you for your efforts! 
I've reinstalled the plugin from Github. Startconnect.sh now contains: "--backend pipe --device /tmp/snapfifo  \ "  and Spotify plays multiroom. 

However, I can hear the sample rate is at 48000Hz while it should be 44100Hz. Also, I've set up Spotify as a dedicated stream but index.js doesn't seem to notice: with this config startconnect.sh should contain '/tmp/spotififo' I believe.

**Comment by Saiyato** [comment]
Hi @VieGie ,

You can check the sample rate in /etc/default/snapserver that's what will be sent out, Spotify will just write out to the fifo-file, depending on your setup (and what settings you have changed) this will affect what is put into the fifo-file. Any resampling before snapserver is following settings in /etc/asound.conf

**Comment by VieGie** [comment]
Hi Saiyato,

In the GUI I have MPD set up at 48000Hz and spotifyconnect (volspotconnect2) at 44100. Spotify is setup as a dedicated stream. I saved all settings in the snapcast and spotify connect plugin. The only change I did afterwards in the terminal was adding `mixer_type      "software"` to mpd.conf and it's template for volume control on the clients.

After your fix startconnect.sh gets written now and a.o. contains:
`--backend pipe --device /tmp/snapfifo  \`

Options in /etc/default/snapserver:
`SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=VOLUMIO-MPD&mode=read -s pipe:///tmp/spotififo?name=VOLUMIO-MULTIROOM&mode=read&sampleformat=44100:16:2 "`

/etc/asound.conf:
`#SNAPCAST
pcm.!snapcast {
        type plug
        slave.pcm snapConverter
}

pcm.writeFile {
        type file
        slave.pcm null
        file "/tmp/spotififo"
        format "raw"
}
#ENDOFSNAPCAST`

Do you see anything out the ordinary in these files? Multiroom mpd plays at 48000 (which is good), but unfortunately Spotify does too (not good).

**Comment by VieGie** [comment]
I wonder if I'm the only one having this problem. :)
@dgarciamontes, I'm very eager to know the result of your testings!

**Comment by ashthespy** [comment]
I just realised, that the recently changed `vollibrespot > v0.2.0` reads a `*.toml` file instead of passing flags directly to it - which is probably going to break snapcast. 
However, this might make it easier for you to specify a new config file, and just link it directly via the `-c snapcast.toml` in `startconnect.sh` 
If you need something special in volibrespot, do let me know.. :-)

**Comment by Saiyato** [comment]
Hi @ashthespy thanks for the heads-up! It's a bit hard to find the time to work on all the issues (divided across the plugins), but I will prioritize this one as it will probably break for everyone installing the new version.

**Comment by dddesign** [comment]
I use Volumio 2.779, Snapcast 2.5.1, volumio spotify connect2 1.0.3
Snapcast is working with local music and internetradios, but not with spotify. Spotify stream I hear on my volumio jack output but not on snapcast. 
Options in /etc/default/snapserver:
`SNAPSERVER_OPTS="-d -s pipe:///tmp/snapfifo?name=Js_MUSICserver&mode=read&sampleformat=44100:16:2&codec=pcm "
`
any ideas?

**Comment by dddesign** [comment]
> Hi @ashthespy thanks for the heads-up! It's a bit hard to find the time to work on all the issues (divided across the plugins), but I will prioritize this one as it will probably break for everyone installing the new version.

any news on this? do you think you can fix this? otherwise I have to downgrade volumio/volllibrespot  to get a working spotify connect multiroom system. thanks for your great work!

**Comment by foreveremain** [comment]
@ashthespy @Saiyato - I'll try a config patch for this but can't locate any docs for the vollibrespot .toml config. Any ideas ?

**Comment by ashthespy** [comment]
There is a sample one in the volspotconnect2 [repo](https://github.com/balbuze/volumio-plugins/blob/master/plugins/music_service/volspotconnect2/volspotify.tmpl) - but don't hesitate to ask if you need something specific :-)

**Comment by foreveremain** [comment]
Thanks - also found https://github.com/ashthespy/Vollibrespot/blob/master/src/config_parser.rs

**Comment by ashthespy** [comment]
Ah yes of course - the [`Output`](https://github.com/ashthespy/Vollibrespot/blob/14384409fb9c30dbfec9c8d932786efabdd9f3ac/src/config_parser.rs#L51-L60) is probably the most interesting for snapcast.

**Comment by Saiyato** [comment]
I'm currently working on a revamp of the server part, I will release two plugins instead of one: a server and a client. And, on top of that, I will release both as apps to install _and_ as Docker containers.

If I'm not mistake this will take care of the output part:
```
sed -i -- 's|device =.*|device = \x27/tmp/snapfifo\x27|g' /data/plugins/music_service/volspotconnect2/volspotify.tmpl
sed -i -- 's|backend =.*|backend = \x27pipe\x27|g' /data/plugins/music_service/volspotconnect2/volspotify.tmpl
```
Update: you will need to run sed as super user ;)

You will need to restart the VolspotConnect plugin for the changes to take effect.

Update 2: just tested this with a newly installed Volumio instance, on a Pi2, with the new script and an Android client. Works just fine after a reboot, not sure why that's needed, it seemed unable to connect to the VolspotConnect instance. Could be just a glitch :)

**Comment by VieGie** [comment]
H Saiyato, did you get MPD playing at 48000 and Spotify at 44100Hz?

**Comment by Saiyato** [comment]
Hi,

The default settings are the ones I use, you can find the new plugin(s) here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
