### ISSUE TITLE
can't install latest plugin on latest volumio images

### ISSUE THREAD

**Issue by karba78** [Saiyato/volumio-snapcast-plugin#75]
tried all of the four latest volumio image to install manually the plugin on a Pi0 
still fails see below
not sure what i should do 
volumio@pi0iqamp:~/snapcast$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
npm WARN notice [SECURITY] parsejson has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=parsejson&version=0.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] parsejson has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=parsejson&version=0.0.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
/bin/mv: target '/tmp/plugins/snapcast.zip' is not a directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/snapcast.zip
/bin/mv: target '/tmp/plugins/snapcast.zip' is not a directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:688:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:749:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by Saiyato** [comment]
Hi @karba78 ,

I will need a little bit more information, but it sounds like you downloaded a zipfile from github and didn't delete the zip before trying `volumio plugin install`

Please post back

**Comment by karba78** [comment]
Thks @Saiyato , You are right this did the trick. this works now; still have an error message (to fast to catch) when disabling the server.  it seems to be with rights on modifying config files
that s ok with me, not using the server
thks much. consider this closed
