### ISSUE TITLE
Can Snapcat stream multiroom  from an arduino zero to Android App clients like snapcast.app?

### ISSUE THREAD

**Issue by abiaygun** [Saiyato/volumio-snapcast-plugin#77]
I just find this tutorial, can you be kind to help me with it please?
Can this plugin do this?
Thank you!
Here what I  just found 

https://www.youtube.com/watch?v=oA0L4tSvPKk

**Comment by Saiyato** [comment]
The Arduino definitely no, the Raspberry Pi Zero: absolutely yes!

You can find the new plugins (Volumio 3 ready) here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
