### ISSUE TITLE
SnapCast 0.2.xxx incompatibility, systemd services issues

### ISSUE THREAD

**Issue by msekoranja** [Saiyato/volumio-snapcast-plugin#80]
I followed manual install from SnapCast to install it on x86 system. The installation instructions from SnapCast GitHub work (note that build fails with the latest 1.74.0 boost, I hav eused 1.71.0).
SnapCast server and client no longer accept log params, etc. So I had to remove these from /lib/systemd/system/snap{server,client}.service.
In addition I needed to change SnapClient group to "audio" since there is on "snapclient" group. With this done, I got both started.

This might help somebody.

**Comment by Saiyato** [comment]
Hi there,

I see I didn't respond to this, I'm actually packing them in containers now. Performance monitoring is still running. So if Docker doesn't add too much overhead, I think that's the way to go (as I compile from code in the containers, which automatically pulls the latest greatest version).
