### ISSUE TITLE
Compiled Snapcast 0.22 for volumio/raspberry pi (bin attached)

### ISSUE THREAD

**Issue by dgarciamontes** [Saiyato/volumio-snapcast-plugin#81]
Hi,

I built snapcast server/client 0.22 and i get it working into a raspberry pi 3.
It was hard to get the bin file working so I decide to share with you all.

Thanks to this version I can use snapweb to control volume.

Please find attached binary files and snapweb:
How to update:

1- Rename /usr/bin/snapclient  and /usr/bin/snapserver to old version
mv /usr/bin/snapclient /usr/bin/snapclient_old
mv /usr/bin/snapserver /usr/bin/snapserver_old

2- Copy new binaries into /usr/bin

3- Change owner and permissions:
chown root:root /usr/bin/snapclient /usr/bin/snapserver
chmod 755 /usr/bin/snapclient /usr/bin/snapserver

4- Copy snapweb folder into /volumio/http/www3
Reboot volumio. Noy you can access to snapweb using http://your.volumio.ip.addr/snapweb

**Files:**
[snapcast_update_volumio_rpi.zip](https://github.com/Saiyato/volumio-snapcast-plugin/files/5360709/snapcast_update_volumio_rpi.zip)

**Comment by Saiyato** [comment]
One extra comment on this, newer versions require different start params, which means not everything will work as before

**Comment by Sirnut** [comment]
@dgarciamontes How has this version 0.22 been working for you? Any advice on how to go about compiling newer releases?

**Comment by dgarciamontes** [comment]
> @dgarciamontes How has this version 0.22 been working for you? Any advice on how to go about compiling newer releases?

It's working fine, I just replace the compiled file by the new one and I changed a some lines on config part (very easy, I don't remember what and why).

I did it in the simpliest way possible. I compiled directly into a raspberry with volumio. The only thing that you will need is considering to put on a swap file, available ram on a raspberry it's not enought and it will crash.

I'm happy to help you and I'm waiting for new compiled versions!

**Comment by Sirnut** [comment]
Good to know. I compiled 0.24 on Linux mint but I haven’t tried using it with the plug-in quite yet. Any chance you could share your config file when you have time so I could compare them to see what changes allowed it to work?

**Comment by Saiyato** [comment]
You can find the compiled binary for 0.22 in the docker image, it's fairly easy to loot docker images. You can find it on Dockerhub: https://hub.docker.com/repository/docker/saiyato/snapclient

I'm working on building 0.24; however that comes with a caveat... the author added Pulse support. The problem with that is that it adds another 25 megs to my image (which I don't want, at least not for this purpose). So what I'm doing is trying to figure out how to compile the binaries using cmake (as opposed to the precompiled Makefiles; which will be removed in the future). This is definitely beyond me... but I think I'm making progress, despite not fully understanding the matter.

**Comment by osdieman** [comment]
Hi Guys.. thanks all for this nice work ..

now i have two rp 3b+ running latest volumio stable 2.907  and have snapcast setup.. this is running ok.. now i wanted to update the snapcast bin's  so followed this tutorial.. now sanpcast does start  server and client.. but the sound is horrable.. it stutters and breaks all the time.. is snapcast 0.15.0  the only proper working version for this setup ?

I did some more findings...  i can update both client versions to 0.22  and this gives no issues so far... so only the server part is basically not working properly when updating to 0.22  this gives really bad sound..

kind regards Osdieman

**Comment by osdieman** [comment]
> One extra comment on this, newer versions require different start params, which means not everything will work as before

what doe we have to change... is this causing my problems ..?

**Comment by Saiyato** [comment]
"horrible" sound can be due to resampling, not all resampling options combined yield good results. Also, results on Volumio might be different from other distro's/eco-systems
```
Problem arise when you put 44.1kHz into the pipe and have the pipe resample to 48kHz.
```

I'm revamping the whole plugin, also cutting it in two (server | client). At the time it looked like the perfect solution to combine the two, but from a maintenance point of view... it's not that great :wink:

See the new repo here: https://github.com/Saiyato/volumio-snapserver-plugin

**Comment by Saiyato** [comment]
Volumio 3 runs on Buster, which means you can use the latest and greatest versions :wink:

You can find the new plugins (Volumio 3 ready) here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
