### ISSUE TITLE
Snapcast server not working?

### ISSUE THREAD

**Issue by DeshDe** [Saiyato/volumio-snapcast-plugin#82]
Hi,

I'm using Volumio 2.8.3.4 on a pi 3 plus. 

Following your manual installation instructions I've installed the snapcast plugin, which hangs at the end at "finishing installation", but showed that the installation was complete earlier. As the plug-in was visible in Volumio, I've enabled and configured it, but it seems, that the server part is not streaming. When I save the snapcast server settings a red message pops up shortly, but is replaced by the green box so fast, I can not read the message. MPT.log shows no entry of this message.

Any idea how to solve this?

Thanks in advance

Edit: Added screenshot of error message (after recording it)

![grafik](https://user-images.githubusercontent.com/72673230/95677752-f7e04680-0bc7-11eb-8606-0c1aa51765f1.png)

**Comment by DeshDe** [comment]
I've solved it somehow: 
1. Install Volumio (rpi image)
2. ssh in and "sudo chmod 777 /etc"
3. Manually install plugin as described in readme.md (hangs at the end btw, but works)
Is it working? yes
Audio quality? poor, need to see what I can do for that (using "-c flac:4" option)

**Comment by Saiyato** [comment]
Hi @DeshDe ,

This is a known issue, the only way around it is:

1. Set the rights way too permissive (as you did)
2. Figure out a way to edit the asound.conf and place it back using root (as opposed to volumio); e.g. in the form of a service

Option 1 will be reset on every update I think, option 2 is the best way... however this requires a lot of extra work and testing. This option has been explored and seems to work, but will take extra time to release.

**Comment by tekdru** [comment]
I am running Volumio 2.861 on RPI 3 B+ with snapcast 2.5.1.  I can't get snapcast to work again even after trying "sudo chmod 777 /etc".  It's the same problem on two of my RPI 3 B+.

here is the log when I try saving snapserver settings.

`info: CALLMETHOD: miscellanea snapcast updateSnapServer [object Object]
info: CoreCommandRouter::executeOnPlugin: snapcast , updateSnapServer
info: Successfully updated snapserver configuration
volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart snapserver
pam_unix(sudo:session): session opened for user root by (uid=0)
Stopping Snapcast server...
info: Touched asound config
Received SIGTERM signal.
info: Cleared previous asound config
info: CMD: /bin/sh /data/plugins/miscellanea/snapcast/snapcast_asound_patch.sh
info: Successfully executed script {/data/plugins/miscellanea/snapcast/snapcast_asound_patch.sh}
Exception in StreamSession::reader(): read_some: End of file
Exception in StreamSession::reader(): read_some: End of file
Exception in ControlSession::reader(): read_until: Bad file descriptor
Exception in ControlSession::reader(): read_until: Bad file descriptor
Exception in ControlSession::reader(): read_until: Bad file descriptor
daemon terminated.
Starting Snapcast server...
Settings file: "/var/lib/snapserver/server.json"
pipe:///tmp/snapfifo?name=VOLUMIO-126&mode=read&sampleformat=44100:16:2
2021-01-09 02-12-11 [Notice] Settings file: "/var/lib/snapserver/server.json"
daemon started
Started Snapcast server.
pam_unix(sudo:session): session closed for user root
Exception in Controller::worker(): read_some: End of file
info: snapserver started
StreamServer::NewConnection: ::ffff:192.168.50.123
Connected to 127.0.0.1
StreamServer::NewConnection: ::ffff:127.0.0.1
`

**Comment by Saiyato** [comment]
Please try the new plugins for this functionality:

https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
