### ISSUE TITLE
"Media Library" files play only through SnapCast, Spotify plays only through local speakers

### ISSUE THREAD

**Issue by mallardtheduck** [Saiyato/volumio-snapcast-plugin#86]
As stated in the title; whenever I play anything from "Media Library" it plays only through SnapCast clients, but whenever I play a Spotify track (either through the crippled "native" Spotify plugin or via Spotify Connect) it plays only through the local speakers.

How do I configure it so everything plays through both?

[asound.conf.txt](https://github.com/Saiyato/volumio-snapcast-plugin/files/5897997/asound.conf.txt)
[mpd.conf.txt](https://github.com/Saiyato/volumio-snapcast-plugin/files/5897998/mpd.conf.txt)

**Comment by Saiyato** [comment]
You'll need the newer version (not available in the store yet). I'm reworking the config pages, to make configuration easier. The Spotify plugin changed its config to a TOML format, which requires new logic to edit. In other words, you'll need to install the plugin manually (pull from GitHub).

**Comment by Saiyato** [comment]
You can find the new versions here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
