### ISSUE TITLE
unable to install on Raspberry Pi 3B

### ISSUE THREAD

**Issue by abc2006** [Saiyato/volumio-snapcast-plugin#90]
Hi, for my the installation process gets stucked at point 6: 
_Wait a few minutes for message saying install was successful._
After 15 Minutes i still wait for: 
_Status :Plugin wird geladen
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip_

Downloading manually via Web-Browser is finished is about 15 seconds.

Cheers, 
Stephan

**Comment by abc2006** [comment]
Possible Duplicate to #89

**Comment by Saiyato** [comment]
Apologies for the late reply, but I revamped this functionality into two separated plugins. This makes maintenance a lot easier:

https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
