### ISSUE TITLE
Any way to add a dedicated Spotify Connect entry for the snapcast?

### ISSUE THREAD

**Issue by anLizard** [Saiyato/volumio-snapcast-plugin#91]
Right now I have two devices, one server and one Client.
![image](https://user-images.githubusercontent.com/48686356/111128613-65c4db80-8575-11eb-9f7a-065f661cfae1.png)

If I play audio on the server (Living Room), I get output on the client (Tobi's Room) as well, but I can't have it play in the Living Room only.
Is there any way I can add an extra entry called "Both Rooms", so I can still control each Raspberry Pi's output separately?

My current backend is volspotconnect2.

Thanks for your help!

**Comment by Saiyato** [comment]
Hi,

If you want to play in the living room only, you can turn off the snapcast plugin on the device in Tobi's room. If you want to add another option in the Spotify app... the only way to do so would be to download a standalone vollibrespot binary and add it as a custom player in the ecosystem. This would be a pretty advanced setup.

You can either:

Living room would need all integrations turned off, and a custom one, with a stand-alone library (note that this will disable playback visualisation in Volumio).

Tobi's room would need a SnapClient enabled, linked to the instance serving the stand-alone library.

OR:

You could download the snapcast app and assign different streams if you want to fiddle with the player setup.

**Comment by anLizard** [comment]
Hmm, okay. In that case I'll play around with the Snapcast app for now. Maybe I'll just run a snapcast server and librespot on my NAS, and connect my volumio pis to that. Thanks!
