### ISSUE TITLE
Is this plugin x86 compatible?

### ISSUE THREAD

**Issue by anLizard** [Saiyato/volumio-snapcast-plugin#93]
Is this plugin x86 compatible? I am trying to turn my Volumio Virtualbox VM on my Intel NUC into a Snapcast server, running the Volumio x86 image.
I followed the instructions in the readme.md, but am constantly running into errors.

Sometimes Volumio can't "start the SnapCastplugin in a fashionable manner", sometimes I get permission errors, sometimes it can't stop the plugin when changing settings.

The SnapCast server doesn't seem to ever actually run. The Snapcast app on my phone can't find it no matter what I try. 
My Raspberry Pi Volumio instance can see the instance on my VM, and I can cast Spotify too, so it isn't a networking issue.

Any help?

**Comment by beankylla** [comment]
It seems [not:](https://github.com/Saiyato/volumio-snapcast-plugin/issues/16)

**Comment by katsaplias** [comment]
I have the same problem, 
would be very helpful if this works

**Comment by Saiyato** [comment]
This project will not be updated anymore, you can find the new plugins here:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin

I separated the server part from the client part, this makes maintenance less stressful.
