### ISSUE TITLE
plugin fails to install with a fresh install on a pi 4

### ISSUE THREAD

**Issue by briantho** [Saiyato/volumio-snapcast-plugin#96]

**Comment by briantho** [comment]
Hi, I'm trying to install this plugin on a freshly installed volumio on a pi 4.
Here are the commands i have run in order after logging in via ssh
git clone https://github.com/Saiyato/volumio-snapcast-plugin.git
cd volumio-snapcast-plugin
rm volumio-snapcast-plugin.zip
volumio plugin install


Here are the errors i get after i run volumio plugin install



This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm notice created a lockfile as package-lock.json. You should commit this file.
Plugin succesfully compressed
Progress: 10
Status :Downloading plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip
Progress: 30
Status :Creating install location
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>Creating install location
Progress: 40
Status :Unpacking plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>Creating install location<br>Unpacking plugin
Progress: 50
Status :Checking for duplicate plugin
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin
Progress: 60
Status :Copying plugin to location
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location
Progress: 70
Status :Installing necessary utilities
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location<br>Installing necessary utilities
Progress: 0
Status :An error occurred while installing the plugin Error
Downloading plugin at http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/snapcast.zip<br>Creating install location<br>Unpacking plugin<br>Checking for duplicate plugin<br>Copying plugin to location<br>Installing necessary utilities<br>An error occurred while installing the plugin Error

**Comment by Saiyato** [comment]
If you cd into the directory before removing the zip, it will fail indeed. Remove the zip before you cd into the dir. :wink:

**Comment by Saiyato** [comment]
The new versions install on my Pi4 with Volumio 3, please try those:
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin

**Comment by briantho** [comment]
ok, thanks for fixing it. I'll probablly try it out sometime after the holidays, as I'm pretty busy at the moment. Thanks for fixing it
