### ISSUE TITLE
airplay not redirected to snapcast

### ISSUE THREAD

**Issue by eggerph** [Saiyato/volumio-snapcast-plugin#97]
Hi everyone

I have managed getting the snapcast plugin to run for my local library playing from a usb stick on the server RPi. 
However, what I would really love is to be able to play to multiple devices via airplay because I am mostly listening to deezer via my iPad. Now I know without Airplay 2 there is no automatic multi-room feature, but I was hoping to be able to stream with airplay to my server and then "distribute" the sound from there. Is this not possible at all or did I set it up incorrectly?

Any help is much appreciated. I even started looking at other solutions like BalenaSound because I am so desperate. But I didn't manage to get that to work yet either and I love Volumio...

**Comment by Saiyato** [comment]
Hi buddy,

AirPlay is a different story altogether, it requires a change in configs that touch on the base of Volumio (persistent change is difficult and breaks the Volumio update process). I due time I will discontinue the current SnapCast plugin setup, I've split the solution into two parts:

1. The server
2. The client

If it's not too difficult, I will merge all changes upstream to this plugin as well. You can follow the progress [here (server)](https://github.com/Saiyato/volumio-snapserver-plugin) and [here (client)](https://github.com/Saiyato/volumio-snapclient-plugin)

**Comment by Saiyato** [comment]
I don't think I will have the time to maintain this plugin anymore, the new ones provide better flexibility.
https://github.com/Saiyato/volumio-snapserver-plugin
https://github.com/Saiyato/volumio-snapclient-plugin
