### ISSUE TITLE
No sound when playing Spotify Connect on client

### ISSUE THREAD

**Issue by anLizard** [Saiyato/volumio-snapcast-plugin#98]
I have the following setup:

Pi 3 - Snapcast Server (no client)
Pi 4 - Snapcast Client (HDMI)
Pi 0 - Snapcast Client (HifiBerry DAC Zero)

On each Pi:
Snapcast plugin v2.5.1 
Volumio 2.917

When playing Spotify Connect on the Volumio instance running the Snapcast client, there is no sound at all.

Playing music on the server correctly makes it play back on the clients, but I need to be able to do individual playback on my clients as well.

Settings on the clients (only difference is the DAC on the Pi Zero):

![image](https://user-images.githubusercontent.com/48686356/136553024-d0445c8d-8c71-45ed-8061-06695cd6f6df.png)
![image](https://user-images.githubusercontent.com/48686356/136553054-e6e8ce19-cf2b-4520-93f0-ba444de72db1.png)
![image](https://user-images.githubusercontent.com/48686356/136553111-c2fab962-52db-4028-95d2-87f153325779.png)
![image](https://user-images.githubusercontent.com/48686356/136553140-4def79bb-268d-4204-a5cf-ba0fd0a8f86e.png)

**Comment by anLizard** [comment]
Playing around some more with the settings, specifically turning off the dedicated stream.
I always end up with one of these scenarios:

1. No sound when playing Spotify on client
2. No sound when playing Web Radio/files on client
3. No sound when playing ANYTHING on client

Playing sound on the server correctly sends the audio to the clients and plays as expected.

**Comment by Saiyato** [comment]
Sorry for the late reply, but this is probable because installing the SnapCast component will overwrite output for the other music services. This is one of the reasons I decided to create separate plugins for the server and client part.

You can find the snapclient plugin here: https://github.com/Saiyato/volumio-snapclient-plugin
But you will need to install manually :wink:

**Comment by anLizard** [comment]
Thank you, I will give the new plugin a try and will report back if I am still having issues!

**Comment by anLizard** [comment]
Oh my god, it works. Thank you so much, this has been plaguing me since forever!
You should advertise the new plugin on this repo, and possibly see if you can get it on the official plugin list as well

**Comment by Saiyato** [comment]
Haha good to hear it solved your issue :smiley: 

It's on my todo list to publish this (and other) plugin(s), but there's so much to do and I have little spare time. So at times I progress much, and then several weeks you will see no progression. :wink:

In other repo's I'm packaging the snapcast components into containers, which makes it even portable to other systems (and architectures).

In short, yes I will publish the plugins, but it will take some testing (and time).
